/* @flavorc
 *
 * PING.java
 * 
 * This file was automatically generated by flavorc
 * from the source file:
 *     'avm.fl'
 *
 * For information on flavorc, visit the Flavor Web site at:
 *     http://www.ee.columbia.edu/flavor
 *
 * -- Do not edit by hand --
 *
 */

package org.avm.elementary.protocol.avm.parser;

import java.io.IOException;
import java.io.InputStream;

import flavor.IBitstream;
import flavor.MapResult;

public class PING extends Message {
	int _longitude;
	int _latitude;

	public static final int MESSAGE_TYPE = 5;

	public PING() {
		this(0, 0);
	}

	public PING(int longitude, int latitude) {
		super(MESSAGE_TYPE);
		_longitude = longitude;
		_latitude = latitude;
	}

	public int getLongitude() {
		return _longitude;
	}

	public void setLongitude(int longitude) {
		_longitude = longitude;
	}

	public int getLatitude() {
		return _latitude;
	}

	public void setLatitude(int latitude) {
		_latitude = latitude;
	}

	public String toString() {
		return "ping: " + super.toString() + " lon = " + _longitude + " lat = "
				+ _latitude;
	}

	public static class DefaultMessageFactory extends MessageFactory {

		protected Message get(InputStream in) throws Exception {
			InputBitstream bs = new InputBitstream(in);
			Message message = new PING();
			message.get(bs);

			return message;
		}
	}

	static {
		MessageFactory.factories.put(new Integer(MESSAGE_TYPE),
				new DefaultMessageFactory());
	}

	public int get(IBitstream _F_bs) throws IOException {
		int _F_ret = 0;
		MapResult _F_mr;
		_F_ret += super.get(_F_bs);
		_longitude = _F_bs.sgetbits(32);
		_latitude = _F_bs.sgetbits(32);
		return _F_ret;
	}

	public int put(IBitstream _F_bs) throws IOException {
		int _F_ret = 0;
		MapResult _F_mr;
		_F_ret += super.put(_F_bs);
		_F_bs.putbits(_longitude, 32);
		_F_bs.putbits(_latitude, 32);
		return _F_ret;
	}
}
