/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.fm6000.system.jni;

class COMVS_SYSTEMJNI {

	static {
		try {
			System.loadLibrary("comvs_system");
		} catch (UnsatisfiedLinkError e) {
			System.err.println("Native code library failed to load. \n" + e);
		}
	}

	public final static native int exec(String jarg1, String jarg2);

	public final static native int kill(int jarg1);

	public final static native int settime(long jarg1);
}
