/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.fm6000.system.jni;

public class COMVS_SYSTEM {
  public static int exec(String name, String args) {
    return COMVS_SYSTEMJNI.exec(name, args);
  }

  public static int kill(int handle) {
    return COMVS_SYSTEMJNI.kill(handle);
  }

  public static int settime(long date) {
    return COMVS_SYSTEMJNI.settime(date);
  }

}
