/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.fm6000.io.jni;

public class COMVS_IO_PIN {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected COMVS_IO_PIN(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(COMVS_IO_PIN obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      COMVS_IOJNI.delete_COMVS_IO_PIN(swigCPtr);
    }
    swigCPtr = 0;
  }

  protected static long[] cArrayUnwrap(COMVS_IO_PIN[] arrayWrapper) {
      long[] cArray = new long[arrayWrapper.length];
      for (int i=0; i<arrayWrapper.length; i++)
        cArray[i] = COMVS_IO_PIN.getCPtr(arrayWrapper[i]);
      return cArray;
  }

  protected static COMVS_IO_PIN[] cArrayWrap(long[] cArray, boolean cMemoryOwn) {
    COMVS_IO_PIN[] arrayWrapper = new COMVS_IO_PIN[cArray.length];
    for (int i=0; i<cArray.length; i++)
      arrayWrapper[i] = new COMVS_IO_PIN(cArray[i], cMemoryOwn);
    return arrayWrapper;
  }

  public void setId(long value) {
    COMVS_IOJNI.COMVS_IO_PIN_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return COMVS_IOJNI.COMVS_IO_PIN_id_get(swigCPtr, this);
  }

  public void setMode(long value) {
    COMVS_IOJNI.COMVS_IO_PIN_mode_set(swigCPtr, this, value);
  }

  public long getMode() {
    return COMVS_IOJNI.COMVS_IO_PIN_mode_get(swigCPtr, this);
  }

  public void setState(long value) {
    COMVS_IOJNI.COMVS_IO_PIN_state_set(swigCPtr, this, value);
  }

  public long getState() {
    return COMVS_IOJNI.COMVS_IO_PIN_state_get(swigCPtr, this);
  }

  public void setChange(long value) {
    COMVS_IOJNI.COMVS_IO_PIN_change_set(swigCPtr, this, value);
  }

  public long getChange() {
    return COMVS_IOJNI.COMVS_IO_PIN_change_get(swigCPtr, this);
  }

  public void setOption1(long value) {
    COMVS_IOJNI.COMVS_IO_PIN_option1_set(swigCPtr, this, value);
  }

  public long getOption1() {
    return COMVS_IOJNI.COMVS_IO_PIN_option1_get(swigCPtr, this);
  }

  public void setOption2(long value) {
    COMVS_IOJNI.COMVS_IO_PIN_option2_set(swigCPtr, this, value);
  }

  public long getOption2() {
    return COMVS_IOJNI.COMVS_IO_PIN_option2_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_void value) {
    COMVS_IOJNI.COMVS_IO_PIN_reserved_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getReserved() {
    long cPtr = COMVS_IOJNI.COMVS_IO_PIN_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public COMVS_IO_PIN() {
    this(COMVS_IOJNI.new_COMVS_IO_PIN(), true);
  }

}
