/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.fm6000.io.jni;

public interface COMVS_IOConstants {
	public final static int COMVS_TRUE = COMVS_IOJNI.COMVS_TRUE_get();
	public final static int COMVS_FALSE = COMVS_IOJNI.COMVS_FALSE_get();
	public final static int IO_DIO_INPUT_0 = COMVS_IOJNI.IO_DIO_INPUT_0_get();
	public final static int IO_DIO_INPUT_1 = COMVS_IOJNI.IO_DIO_INPUT_1_get();
	public final static int IO_DIO_INPUT_2 = COMVS_IOJNI.IO_DIO_INPUT_2_get();
	public final static int IO_DIO_INPUT_3 = COMVS_IOJNI.IO_DIO_INPUT_3_get();
	public final static int IO_DIO_INPUT_4 = COMVS_IOJNI.IO_DIO_INPUT_4_get();
	public final static int IO_DIO_INPUT_5 = COMVS_IOJNI.IO_DIO_INPUT_5_get();
	public final static int IO_DIO_INPUT_6 = COMVS_IOJNI.IO_DIO_INPUT_6_get();
	public final static int IO_DIO_INPUT_7 = COMVS_IOJNI.IO_DIO_INPUT_7_get();
	public final static int IO_DIO_OUTPUT_0 = COMVS_IOJNI.IO_DIO_OUTPUT_0_get();
	public final static int IO_DIO_OUTPUT_1 = COMVS_IOJNI.IO_DIO_OUTPUT_1_get();
	public final static int IO_DIO_OUTPUT_2 = COMVS_IOJNI.IO_DIO_OUTPUT_2_get();
	public final static int IO_DIO_OUTPUT_3 = COMVS_IOJNI.IO_DIO_OUTPUT_3_get();
	public final static int IO_DIO_OUTPUT_4 = COMVS_IOJNI.IO_DIO_OUTPUT_4_get();
	public final static int IO_DIO_OUTPUT_5 = COMVS_IOJNI.IO_DIO_OUTPUT_5_get();
	public final static int IO_DIO_OUTPUT_6 = COMVS_IOJNI.IO_DIO_OUTPUT_6_get();
	public final static int IO_DIO_OUTPUT_7 = COMVS_IOJNI.IO_DIO_OUTPUT_7_get();
	public final static int IO_AIO_INPUT_0 = COMVS_IOJNI.IO_AIO_INPUT_0_get();
	public final static int IO_AIO_INPUT_1 = COMVS_IOJNI.IO_AIO_INPUT_1_get();
	public final static int IO_AIO_INPUT_2 = COMVS_IOJNI.IO_AIO_INPUT_2_get();
	public final static int IO_AIO_INPUT_3 = COMVS_IOJNI.IO_AIO_INPUT_3_get();
	public final static int IO_AIO_INPUT_4 = COMVS_IOJNI.IO_AIO_INPUT_4_get();
	public final static int IO_AIO_INPUT_5 = COMVS_IOJNI.IO_AIO_INPUT_5_get();
	public final static int IO_AIO_INPUT_6 = COMVS_IOJNI.IO_AIO_INPUT_6_get();
	public final static int IO_AIO_INPUT_7 = COMVS_IOJNI.IO_AIO_INPUT_7_get();
	public final static int IO_AIO_INPUT_8 = COMVS_IOJNI.IO_AIO_INPUT_8_get();
	public final static int IO_AIO_INPUT_9 = COMVS_IOJNI.IO_AIO_INPUT_9_get();
	public final static int IO_AIO_INPUT_10 = COMVS_IOJNI.IO_AIO_INPUT_10_get();
	public final static int IO_AIO_INPUT_11 = COMVS_IOJNI.IO_AIO_INPUT_11_get();
	public final static int IO_MODE_DIO_INPUT = COMVS_IOJNI
			.IO_MODE_DIO_INPUT_get();
	public final static int IO_MODE_DIO_OUTPUT = COMVS_IOJNI
			.IO_MODE_DIO_OUTPUT_get();
	public final static int IO_MODE_AIO_INPUT = COMVS_IOJNI
			.IO_MODE_AIO_INPUT_get();
	public final static int IO_DIRECT_READ = COMVS_IOJNI.IO_DIRECT_READ_get();
	public final static int IO_EVENT_READ = COMVS_IOJNI.IO_EVENT_READ_get();
	public final static int IO_NOTIMEOUT = COMVS_IOJNI.IO_NOTIMEOUT_get();
}
