/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.fm6000.io.jni;

public class COMVS_IO implements COMVS_IOConstants {
	public static int open(String name) {
		return COMVS_IOJNI.open(name);
	}

	public static void close(int handle) {
		COMVS_IOJNI.close(handle);
	}

	public static long read(int handle, COMVS_IO_PIN[] data, long size) {
		return COMVS_IOJNI.read(handle, COMVS_IO_PIN.cArrayUnwrap(data), size);
	}

	public static long write(int handle, COMVS_IO_PIN[] data, long size) {
		return COMVS_IOJNI.write(handle, COMVS_IO_PIN.cArrayUnwrap(data), size);
	}

}
