/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.fm6000.io.jni;

public class COMVS_IO_PINS {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected COMVS_IO_PINS(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(COMVS_IO_PINS obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			COMVS_IOJNI.delete_COMVS_IO_PINS(swigCPtr);
		}
		swigCPtr = 0;
	}

	public void setNbofpins(long value) {
		COMVS_IOJNI.COMVS_IO_PINS_nbofpins_set(swigCPtr, this, value);
	}

	public long getNbofpins() {
		return COMVS_IOJNI.COMVS_IO_PINS_nbofpins_get(swigCPtr, this);
	}

	public void setPin(COMVS_IO_PIN value) {
		COMVS_IOJNI.COMVS_IO_PINS_pin_set(swigCPtr, this, COMVS_IO_PIN
				.getCPtr(value), value);
	}

	public COMVS_IO_PIN getPin() {
		long cPtr = COMVS_IOJNI.COMVS_IO_PINS_pin_get(swigCPtr, this);
		return (cPtr == 0) ? null : new COMVS_IO_PIN(cPtr, false);
	}

	public void setReserved(SWIGTYPE_p_void value) {
		COMVS_IOJNI.COMVS_IO_PINS_reserved_set(swigCPtr, this, SWIGTYPE_p_void
				.getCPtr(value));
	}

	public SWIGTYPE_p_void getReserved() {
		long cPtr = COMVS_IOJNI.COMVS_IO_PINS_reserved_get(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
	}

	public COMVS_IO_PINS() {
		this(COMVS_IOJNI.new_COMVS_IO_PINS(), true);
	}

}
