/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTELC__)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <windows.h>
#include <COMVS_AC97.h>


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_COMVS_1TRUE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 0xff;
  
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_COMVS_1FALSE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 0x0;
  
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Mute_1out_1Master(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_Mute_out_Master(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Mute_1out_1HeadPhone(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_Mute_out_HeadPhone(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Mute_1out_1MonoOut(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_Mute_out_MonoOut(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Mute_1in_1Beep(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_Mute_in_Beep(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Mute_1in_1Phone(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_Mute_in_Phone(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Mute_1in_1Microphone(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_Mute_in_Microphone(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Mute_1in_1LineIn(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_Mute_in_LineIn(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Mute_1in_1CD(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_Mute_in_CD(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Mute_1in_1Video(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_Mute_in_Video(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Mute_1in_1Aux(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_Mute_in_Aux(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Mute_1in_1PCM(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_Mute_in_PCM(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Is_1Mute_1out_1Master(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_Is_Mute_out_Master(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Is_1Mute_1out_1HeadPhone(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_Is_Mute_out_HeadPhone(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Is_1Mute_1out_1MonoOut(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_Is_Mute_out_MonoOut(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Is_1Mute_1in_1Beep(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_Is_Mute_in_Beep(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Is_1Mute_1in_1Phone(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_Is_Mute_in_Phone(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Is_1Mute_1in_1Microphone(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_Is_Mute_in_Microphone(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Is_1Mute_1in_1LineIn(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_Is_Mute_in_LineIn(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Is_1Mute_1in_1CD(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_Is_Mute_in_CD(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Is_1Mute_1in_1Video(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_Is_Mute_in_Video(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Is_1Mute_1in_1Aux(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_Is_Mute_in_Aux(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1Is_1Mute_1in_1PCM(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_Is_Mute_in_PCM(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1GetGain_1out_1Master(JNIEnv *jenv, jclass jcls, jshortArray jarg1, jshortArray jarg2) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  unsigned char temp2 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg2 = &temp2; 
  }
  result = (unsigned char)Comvs_GetGain_out_Master(arg1,arg2);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  {
    jshort jvalue = (jshort)temp2;
    (*jenv)->SetShortArrayRegion(jenv, jarg2, 0, 1, &jvalue);
  }
  
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1GetGain_1out_1HeadPhone(JNIEnv *jenv, jclass jcls, jshortArray jarg1, jshortArray jarg2) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  unsigned char temp2 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg2 = &temp2; 
  }
  result = (unsigned char)Comvs_GetGain_out_HeadPhone(arg1,arg2);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  {
    jshort jvalue = (jshort)temp2;
    (*jenv)->SetShortArrayRegion(jenv, jarg2, 0, 1, &jvalue);
  }
  
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1GetGain_1out_1MonoOut(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_GetGain_out_MonoOut(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1GetGain_1in_1Beep(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_GetGain_in_Beep(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1GetGain_1in_1Phone(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_GetGain_in_Phone(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1GetGain_1in_1Microphone(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_GetGain_in_Microphone(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1GetGain_1in_1LineIn(JNIEnv *jenv, jclass jcls, jshortArray jarg1, jshortArray jarg2) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  unsigned char temp2 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg2 = &temp2; 
  }
  result = (unsigned char)Comvs_GetGain_in_LineIn(arg1,arg2);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  {
    jshort jvalue = (jshort)temp2;
    (*jenv)->SetShortArrayRegion(jenv, jarg2, 0, 1, &jvalue);
  }
  
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1GetGain_1in_1CD(JNIEnv *jenv, jclass jcls, jshortArray jarg1, jshortArray jarg2) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  unsigned char temp2 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg2 = &temp2; 
  }
  result = (unsigned char)Comvs_GetGain_in_CD(arg1,arg2);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  {
    jshort jvalue = (jshort)temp2;
    (*jenv)->SetShortArrayRegion(jenv, jarg2, 0, 1, &jvalue);
  }
  
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1GetGain_1in_1Video(JNIEnv *jenv, jclass jcls, jshortArray jarg1, jshortArray jarg2) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  unsigned char temp2 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg2 = &temp2; 
  }
  result = (unsigned char)Comvs_GetGain_in_Video(arg1,arg2);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  {
    jshort jvalue = (jshort)temp2;
    (*jenv)->SetShortArrayRegion(jenv, jarg2, 0, 1, &jvalue);
  }
  
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1GetGain_1in_1Aux(JNIEnv *jenv, jclass jcls, jshortArray jarg1, jshortArray jarg2) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  unsigned char temp2 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg2 = &temp2; 
  }
  result = (unsigned char)Comvs_GetGain_in_Aux(arg1,arg2);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  {
    jshort jvalue = (jshort)temp2;
    (*jenv)->SetShortArrayRegion(jenv, jarg2, 0, 1, &jvalue);
  }
  
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1GetGain_1in_1PCM(JNIEnv *jenv, jclass jcls, jshortArray jarg1, jshortArray jarg2) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  unsigned char temp2 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg2 = &temp2; 
  }
  result = (unsigned char)Comvs_GetGain_in_PCM(arg1,arg2);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  {
    jshort jvalue = (jshort)temp2;
    (*jenv)->SetShortArrayRegion(jenv, jarg2, 0, 1, &jvalue);
  }
  
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1SetGain_1out_1Master(JNIEnv *jenv, jclass jcls, jshort jarg1, jshort jarg2) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char arg2 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  arg2 = (unsigned char)jarg2; 
  result = (unsigned char)Comvs_SetGain_out_Master(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1SetGain_1out_1HeadPhone(JNIEnv *jenv, jclass jcls, jshort jarg1, jshort jarg2) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char arg2 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  arg2 = (unsigned char)jarg2; 
  result = (unsigned char)Comvs_SetGain_out_HeadPhone(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1SetGain_1out_1MonoOut(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_SetGain_out_MonoOut(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1SetGain_1in_1Beep(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_SetGain_in_Beep(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1SetGain_1in_1Phone(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_SetGain_in_Phone(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1SetGain_1in_1Microphone(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_SetGain_in_Microphone(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1SetGain_1in_1LineIn(JNIEnv *jenv, jclass jcls, jshort jarg1, jshort jarg2) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char arg2 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  arg2 = (unsigned char)jarg2; 
  result = (unsigned char)Comvs_SetGain_in_LineIn(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1SetGain_1in_1CD(JNIEnv *jenv, jclass jcls, jshort jarg1, jshort jarg2) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char arg2 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  arg2 = (unsigned char)jarg2; 
  result = (unsigned char)Comvs_SetGain_in_CD(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1SetGain_1in_1Video(JNIEnv *jenv, jclass jcls, jshort jarg1, jshort jarg2) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char arg2 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  arg2 = (unsigned char)jarg2; 
  result = (unsigned char)Comvs_SetGain_in_Video(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1SetGain_1in_1Aux(JNIEnv *jenv, jclass jcls, jshort jarg1, jshort jarg2) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char arg2 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  arg2 = (unsigned char)jarg2; 
  result = (unsigned char)Comvs_SetGain_in_Aux(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1SetGain_1in_1PCM(JNIEnv *jenv, jclass jcls, jshort jarg1, jshort jarg2) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char arg2 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  arg2 = (unsigned char)jarg2; 
  result = (unsigned char)Comvs_SetGain_in_PCM(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1SetExtraGain_1in_1Microphone(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_SetExtraGain_in_Microphone(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1GetExtraGain_1in_1Microphone(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_GetExtraGain_in_Microphone(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1SetMicro_1MonoOut(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jshort jresult = 0 ;
  unsigned char arg1 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  result = (unsigned char)Comvs_SetMicro_MonoOut(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_avm_device_fm6000_ac97_jni_COMVS_1AC97JNI_Comvs_1GetMicro_1MonoOut(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jshort jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char result;
  unsigned char temp1 ;
  
  (void)jenv;
  (void)jcls;
  {
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg1) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg1 = &temp1; 
  }
  result = (unsigned char)Comvs_GetMicro_MonoOut(arg1);
  jresult = (jshort)result; 
  {
    jshort jvalue = (jshort)temp1;
    (*jenv)->SetShortArrayRegion(jenv, jarg1, 0, 1, &jvalue);
  }
  
  return jresult;
}


#ifdef __cplusplus
}
#endif

