/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI */

#ifndef _Included_org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
#define _Included_org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_SwitchOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1SwitchOff
  (JNIEnv *, jclass);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_SwitchOffAlt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1SwitchOffAlt
  (JNIEnv *, jclass);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_ColdReboot
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1ColdReboot
  (JNIEnv *, jclass);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_Modem_SwitchOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1Modem_1SwitchOn
  (JNIEnv *, jclass);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_Modem_SwitchOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1Modem_1SwitchOff
  (JNIEnv *, jclass);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_GPS_SwitchOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1GPS_1SwitchOn
  (JNIEnv *, jclass);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_GPS_SwitchOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1GPS_1SwitchOff
  (JNIEnv *, jclass);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_Accelerometer_SwitchOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1Accelerometer_1SwitchOn
  (JNIEnv *, jclass);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_Accelerometer_SwitchOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1Accelerometer_1SwitchOff
  (JNIEnv *, jclass);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_CAN_SwitchOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1CAN_1SwitchOn
  (JNIEnv *, jclass);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_CAN_SwitchOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1CAN_1SwitchOff
  (JNIEnv *, jclass);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_GetPowerSource
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1GetPowerSource
  (JNIEnv *, jclass);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_StopPowerEvent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1StopPowerEvent
  (JNIEnv *, jclass);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_GetPowerSourceAlt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1GetPowerSourceAlt
  (JNIEnv *, jclass);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_WaitPowerEvent
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1WaitPowerEvent
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_SetRTCWakeUp
 * Signature: (Lorg/avm/device/fm6000/power/jni/POWERMANAGEMENT_CALENDAR;I)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1SetRTCWakeUp
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_GetRTCWakeUp
 * Signature: (Lorg/avm/device/fm6000/power/jni/POWERMANAGEMENT_CALENDAR;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1GetRTCWakeUp
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_avm_device_fm6000_power_jni_COMVS_0005fPOWERMANAGEMENTJNI
 * Method:    Comvs_GetWakeupSource
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_fm6000_power_jni_COMVS_1POWERMANAGEMENTJNI_Comvs_1GetWakeupSource
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
