/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.fm6000.network.jni;

public class COMVS_NETCONFIG implements COMVS_NETCONFIGConstants {

	public static int Comvs_AddRouteToInterface(String adpaterName,
			COMVS_NETCONFIG_ROUTE r) throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_AddRouteToInterface(adpaterName, r);
	}

	public static int Comvs_DeleteRouteOfInterface(String adpaterName,
			COMVS_NETCONFIG_ROUTE r) throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_DeleteRouteOfInterface(adpaterName, r);
	}

	public static int Comvs_ModifyRouteOfInterface(String adpaterName,
			COMVS_NETCONFIG_ROUTE oldRoute, COMVS_NETCONFIG_ROUTE newRoute)
			throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_ModifyRouteOfInterface(adpaterName,
				oldRoute, newRoute);
	}

	public static int Comvs_RenewDHCPLease(String adapterName)
			throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_RenewDHCPLease(adapterName);
	}

	public static int Comvs_ReleaseDHCPLease(String adapterName)
			throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_ReleaseDHCPLease(adapterName);
	}

	public static int Comvs_SetGlobalProperty(int property, Object obj)
			throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_SetGlobalProperty(property, obj);
	}

	public static int Comvs_GetGlobalProperty(int property, Object obj)
			throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_GetGlobalProperty(property, obj);
	}

	public static int Comvs_SetDHCPConfiguration(String adapterName,
			COMVS_NETCONFIG_DCHP_CONFIGURATION config)
			throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_SetDHCPConfiguration(adapterName,
				config);
	}

	public static int Comvs_SetDNSConfiguration(String adapterName,
			COMVS_NETCONFIG_DNS_CONFIGURATION config) throws NetConfigException {
		return COMVS_NETCONFIGJNI
				.Comvs_SetDNSConfiguration(adapterName, config);
	}

	public static int Comvs_SetWINSConfiguration(String adapterName,
			COMVS_NETCONFIG_WINS_CONFIGURATION config)
			throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_SetWINSConfiguration(adapterName,
				config);
	}

	public static int Comvs_SetProperty(String adapterName, int property,
			Object obj) throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_SetProperty(adapterName, property, obj);
	}

	public static Object Comvs_GetProperty(String adapterName, int property)
			throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_GetProperty(adapterName, property);
	}

	public static int Comvs_ReleaseIPAddress(String adapterName,
			COMVS_NETCONFIG_IP ip) throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_ReleaseIPAddress(adapterName, ip);
	}

	public static int Comvs_RegisterIPAddress(String adapterName,
			COMVS_NETCONFIG_IP ip, COMVS_NETCONFIG_IP mask)
			throws NetConfigException {
		return COMVS_NETCONFIGJNI
				.Comvs_RegisterIPAddress(adapterName, ip, mask);
	}

	public static COMVS_NETCONFIG_ROUTE[] Comvs_ListRoutesOfInterface(
			String adapterName) throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_ListRoutesOfInterface(adapterName);
	}

	public static COMVS_NETCONFIG_ROUTE[] Comvs_ListRoutes()
			throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_ListRoutes();
	}

	public static COMVS_NETCONFIG_IP[] Comvs_ListIPAddresses(String adapterName)
			throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_ListIPAddresses(adapterName);
	}

	public static COMVS_NETCONFIG_IP[] Comvs_ListIP() throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_ListIP();
	}

	public static String[] Comvs_ListInterfaces() throws NetConfigException {
		return COMVS_NETCONFIGJNI.Comvs_ListInterfaces();
	}

}
