/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_avm_device_connection_can_Connection */

#ifndef _Included_org_avm_device_connection_can_Connection
#define _Included_org_avm_device_connection_can_Connection
#ifdef __cplusplus
extern "C" {
#endif
#undef org_avm_device_connection_can_Connection_DEFAULT_TIMEOUT
#define org_avm_device_connection_can_Connection_DEFAULT_TIMEOUT 100L
#undef org_avm_device_connection_can_Connection_UNOPENED
#define org_avm_device_connection_can_Connection_UNOPENED 0L
#undef org_avm_device_connection_can_Connection_OPEN
#define org_avm_device_connection_can_Connection_OPEN 1L
#undef org_avm_device_connection_can_Connection_CLOSED
#define org_avm_device_connection_can_Connection_CLOSED 2L
/*
 * Class:     org_avm_device_connection_can_Connection
 * Method:    openImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_connection_can_Connection_openImpl
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_avm_device_connection_can_Connection
 * Method:    configureImpl
 * Signature: (IIII[I[I)V
 */
JNIEXPORT void JNICALL Java_org_avm_device_connection_can_Connection_configureImpl
  (JNIEnv *, jobject, jint, jint, jint, jint, jintArray, jintArray);

/*
 * Class:     org_avm_device_connection_can_Connection
 * Method:    closeImpl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_avm_device_connection_can_Connection_closeImpl
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_avm_device_connection_can_Connection
 * Method:    readImpl
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_connection_can_Connection_readImpl
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     org_avm_device_connection_can_Connection
 * Method:    writeImpl
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_connection_can_Connection_writeImpl
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     org_avm_device_connection_can_Connection
 * Method:    availableImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_connection_can_Connection_availableImpl
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
