/* @flavorc
 *
 * Anomalie.java
 * 
 * This file was automatically generated by flavorc
 * from the source file:
 *     'phoebus.fl'
 *
 * For information on flavorc, visit the Flavor Web site at:
 *     http://www.ee.columbia.edu/flavor
 *
 * -- Do not edit by hand --
 *
 */

package org.avm.business.protocol.phoebus;
import java.io.IOException;

import flavor.IBitstream;
import flavor.MapResult;

public class Anomalie {
    int _alarme_0;
    int _alarme_1;
    int _alarme_2;
    int _alarme_3;
    int _alarme_4;
    int _alarme_5;
    int _alarme_6;
    int _alarme_7;
    int _alarme_8;
    int _alarme_9;
    int _alarme_10;
    int _alarme_11;
    int _alarme_12;
    int _alarme_13;
    int _alarme_14;
    int _alarme_15;
    int _alarme_16;
    int _alarme_17;
    int _alarme_18;
    int _alarme_19;
    int _alarme_20;
    int _alarme_21;
    int _alarme_22;
    int _alarme_23;
    int _alarme_24;
    int _alarme_25;
    int _alarme_26;
    int _alarme_27;
    int _alarme_28;
    int _alarme_29;
    int _alarme_30;
    int _alarme_31;
    
	public Anomalie() {

	}

	public Anomalie(int alarme_0, int alarme_1, int alarme_2, int alarme_3,
			int alarme_4, int alarme_5, int alarme_6, int alarme_7,
			int alarme_8, int alarme_9, int alarme_10, int alarme_11,
			int alarme_12, int alarme_13, int alarme_14, int alarme_15,
			int alarme_16, int alarme_17, int alarme_18, int alarme_19,
			int alarme_20, int alarme_21, int alarme_22, int alarme_23,
			int alarme_24, int alarme_25, int alarme_26, int alarme_27,
			int alarme_28, int alarme_29, int alarme_30, int alarme_31) {
		super();
		_alarme_0 = alarme_0;
		_alarme_1 = alarme_1;
		_alarme_2 = alarme_2;
		_alarme_3 = alarme_3;
		_alarme_4 = alarme_4;
		_alarme_5 = alarme_5;
		_alarme_6 = alarme_6;
		_alarme_7 = alarme_7;
		_alarme_8 = alarme_8;
		_alarme_9 = alarme_9;
		_alarme_10 = alarme_10;
		_alarme_11 = alarme_11;
		_alarme_12 = alarme_12;
		_alarme_13 = alarme_13;
		_alarme_14 = alarme_14;
		_alarme_15 = alarme_15;
		_alarme_16 = alarme_16;
		_alarme_17 = alarme_17;
		_alarme_18 = alarme_18;
		_alarme_19 = alarme_19;
		_alarme_20 = alarme_20;
		_alarme_21 = alarme_21;
		_alarme_22 = alarme_22;
		_alarme_23 = alarme_23;
		_alarme_24 = alarme_24;
		_alarme_25 = alarme_25;
		_alarme_26 = alarme_26;
		_alarme_27 = alarme_27;
		_alarme_28 = alarme_28;
		_alarme_29 = alarme_29;
		_alarme_30 = alarme_30;
		_alarme_31 = alarme_31;
	}

	public int getAlarme_0() {
		return _alarme_0;
	}

	public void setAlarme_0(int alarme_0) {
		_alarme_0 = alarme_0;
	}

	public int getAlarme_1() {
		return _alarme_1;
	}

	public void setAlarme_1(int alarme_1) {
		_alarme_1 = alarme_1;
	}

	public int getAlarme_10() {
		return _alarme_10;
	}

	public void setAlarme_10(int alarme_10) {
		_alarme_10 = alarme_10;
	}

	public int getAlarme_11() {
		return _alarme_11;
	}

	public void setAlarme_11(int alarme_11) {
		_alarme_11 = alarme_11;
	}

	public int getAlarme_12() {
		return _alarme_12;
	}

	public void setAlarme_12(int alarme_12) {
		_alarme_12 = alarme_12;
	}

	public int getAlarme_13() {
		return _alarme_13;
	}

	public void setAlarme_13(int alarme_13) {
		_alarme_13 = alarme_13;
	}

	public int getAlarme_14() {
		return _alarme_14;
	}

	public void setAlarme_14(int alarme_14) {
		_alarme_14 = alarme_14;
	}

	public int getAlarme_15() {
		return _alarme_15;
	}

	public void setAlarme_15(int alarme_15) {
		_alarme_15 = alarme_15;
	}

	public int getAlarme_16() {
		return _alarme_16;
	}

	public void setAlarme_16(int alarme_16) {
		_alarme_16 = alarme_16;
	}

	public int getAlarme_17() {
		return _alarme_17;
	}

	public void setAlarme_17(int alarme_17) {
		_alarme_17 = alarme_17;
	}

	public int getAlarme_18() {
		return _alarme_18;
	}

	public void setAlarme_18(int alarme_18) {
		_alarme_18 = alarme_18;
	}

	public int getAlarme_19() {
		return _alarme_19;
	}

	public void setAlarme_19(int alarme_19) {
		_alarme_19 = alarme_19;
	}

	public int getAlarme_2() {
		return _alarme_2;
	}

	public void setAlarme_2(int alarme_2) {
		_alarme_2 = alarme_2;
	}

	public int getAlarme_20() {
		return _alarme_20;
	}

	public void setAlarme_20(int alarme_20) {
		_alarme_20 = alarme_20;
	}

	public int getAlarme_21() {
		return _alarme_21;
	}

	public void setAlarme_21(int alarme_21) {
		_alarme_21 = alarme_21;
	}

	public int getAlarme_22() {
		return _alarme_22;
	}

	public void setAlarme_22(int alarme_22) {
		_alarme_22 = alarme_22;
	}

	public int getAlarme_23() {
		return _alarme_23;
	}

	public void setAlarme_23(int alarme_23) {
		_alarme_23 = alarme_23;
	}

	public int getAlarme_24() {
		return _alarme_24;
	}

	public void setAlarme_24(int alarme_24) {
		_alarme_24 = alarme_24;
	}

	public int getAlarme_25() {
		return _alarme_25;
	}

	public void setAlarme_25(int alarme_25) {
		_alarme_25 = alarme_25;
	}

	public int getAlarme_26() {
		return _alarme_26;
	}

	public void setAlarme_26(int alarme_26) {
		_alarme_26 = alarme_26;
	}

	public int getAlarme_27() {
		return _alarme_27;
	}

	public void setAlarme_27(int alarme_27) {
		_alarme_27 = alarme_27;
	}

	public int getAlarme_28() {
		return _alarme_28;
	}

	public void setAlarme_28(int alarme_28) {
		_alarme_28 = alarme_28;
	}

	public int getAlarme_29() {
		return _alarme_29;
	}

	public void setAlarme_29(int alarme_29) {
		_alarme_29 = alarme_29;
	}

	public int getAlarme_3() {
		return _alarme_3;
	}

	public void setAlarme_3(int alarme_3) {
		_alarme_3 = alarme_3;
	}

	public int getAlarme_30() {
		return _alarme_30;
	}

	public void setAlarme_30(int alarme_30) {
		_alarme_30 = alarme_30;
	}

	public int getAlarme_31() {
		return _alarme_31;
	}

	public void setAlarme_31(int alarme_31) {
		_alarme_31 = alarme_31;
	}

	public int getAlarme_4() {
		return _alarme_4;
	}

	public void setAlarme_4(int alarme_4) {
		_alarme_4 = alarme_4;
	}

	public int getAlarme_5() {
		return _alarme_5;
	}

	public void setAlarme_5(int alarme_5) {
		_alarme_5 = alarme_5;
	}

	public int getAlarme_6() {
		return _alarme_6;
	}

	public void setAlarme_6(int alarme_6) {
		_alarme_6 = alarme_6;
	}

	public int getAlarme_7() {
		return _alarme_7;
	}

	public void setAlarme_7(int alarme_7) {
		_alarme_7 = alarme_7;
	}

	public int getAlarme_8() {
		return _alarme_8;
	}

	public void setAlarme_8(int alarme_8) {
		_alarme_8 = alarme_8;
	}

	public int getAlarme_9() {
		return _alarme_9;
	}

	public void setAlarme_9(int alarme_9) {
		_alarme_9 = alarme_9;
	}

	public String toString() {
		return "[" + _alarme_0 + "" + _alarme_1 + "" + _alarme_2
				+ "" + _alarme_3 + "" + _alarme_4 + "" + _alarme_5 + ""
				+ _alarme_6 + "" + _alarme_7 + "" + _alarme_8 + "" + _alarme_9
				+ "" + _alarme_10 + "" + _alarme_11 + "" + _alarme_12 + ""
				+ _alarme_13 + "" + _alarme_14 + "" + _alarme_15 + ""
				+ _alarme_16 + "" + _alarme_17 + "" + _alarme_18 + ""
				+ _alarme_19 + "" + _alarme_20 + "" + _alarme_21 + ""
				+ _alarme_22 + "" + _alarme_23 + "" + _alarme_24 + ""
				+ _alarme_25 + "" + _alarme_26 + "" + _alarme_27 + ""
				+ _alarme_28 + "" + _alarme_29 + "" + _alarme_30 + ""
				+ _alarme_31 + "]";
	}
	

    public int get(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _alarme_0 = _F_bs.getbits(1);
        _alarme_1 = _F_bs.getbits(1);
        _alarme_2 = _F_bs.getbits(1);
        _alarme_3 = _F_bs.getbits(1);
        _alarme_4 = _F_bs.getbits(1);
        _alarme_5 = _F_bs.getbits(1);
        _alarme_6 = _F_bs.getbits(1);
        _alarme_7 = _F_bs.getbits(1);
        _alarme_8 = _F_bs.getbits(1);
        _alarme_9 = _F_bs.getbits(1);
        _alarme_10 = _F_bs.getbits(1);
        _alarme_11 = _F_bs.getbits(1);
        _alarme_12 = _F_bs.getbits(1);
        _alarme_13 = _F_bs.getbits(1);
        _alarme_14 = _F_bs.getbits(1);
        _alarme_15 = _F_bs.getbits(1);
        _alarme_16 = _F_bs.getbits(1);
        _alarme_17 = _F_bs.getbits(1);
        _alarme_18 = _F_bs.getbits(1);
        _alarme_19 = _F_bs.getbits(1);
        _alarme_20 = _F_bs.getbits(1);
        _alarme_21 = _F_bs.getbits(1);
        _alarme_22 = _F_bs.getbits(1);
        _alarme_23 = _F_bs.getbits(1);
        _alarme_24 = _F_bs.getbits(1);
        _alarme_25 = _F_bs.getbits(1);
        _alarme_26 = _F_bs.getbits(1);
        _alarme_27 = _F_bs.getbits(1);
        _alarme_28 = _F_bs.getbits(1);
        _alarme_29 = _F_bs.getbits(1);
        _alarme_30 = _F_bs.getbits(1);
        _alarme_31 = _F_bs.getbits(1);
        return _F_ret;
    }

    public int put(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _F_bs.putbits(_alarme_0, 1);
        _F_bs.putbits(_alarme_1, 1);
        _F_bs.putbits(_alarme_2, 1);
        _F_bs.putbits(_alarme_3, 1);
        _F_bs.putbits(_alarme_4, 1);
        _F_bs.putbits(_alarme_5, 1);
        _F_bs.putbits(_alarme_6, 1);
        _F_bs.putbits(_alarme_7, 1);
        _F_bs.putbits(_alarme_8, 1);
        _F_bs.putbits(_alarme_9, 1);
        _F_bs.putbits(_alarme_10, 1);
        _F_bs.putbits(_alarme_11, 1);
        _F_bs.putbits(_alarme_12, 1);
        _F_bs.putbits(_alarme_13, 1);
        _F_bs.putbits(_alarme_14, 1);
        _F_bs.putbits(_alarme_15, 1);
        _F_bs.putbits(_alarme_16, 1);
        _F_bs.putbits(_alarme_17, 1);
        _F_bs.putbits(_alarme_18, 1);
        _F_bs.putbits(_alarme_19, 1);
        _F_bs.putbits(_alarme_20, 1);
        _F_bs.putbits(_alarme_21, 1);
        _F_bs.putbits(_alarme_22, 1);
        _F_bs.putbits(_alarme_23, 1);
        _F_bs.putbits(_alarme_24, 1);
        _F_bs.putbits(_alarme_25, 1);
        _F_bs.putbits(_alarme_26, 1);
        _F_bs.putbits(_alarme_27, 1);
        _F_bs.putbits(_alarme_28, 1);
        _F_bs.putbits(_alarme_29, 1);
        _F_bs.putbits(_alarme_30, 1);
        _F_bs.putbits(_alarme_31, 1);
        return _F_ret;
    }
}
