/* @flavorc
 *
 * ChampsOptionnels.java
 * 
 * This file was automatically generated by flavorc
 * from the source file:
 *     'phoebus.fl'
 *
 * For information on flavorc, visit the Flavor Web site at:
 *     http://www.ee.columbia.edu/flavor
 *
 * -- Do not edit by hand --
 *
 */

package org.avm.business.protocol.phoebus;
import java.io.IOException;

import flavor.IBitstream;
import flavor.MapResult;

public class ChampsOptionnels {
    int _date;
    int _position;
    int _service;
    int _reference;
    int _progression;
    int _programmation;
    int _anomalie;
    int _options;
    
	public ChampsOptionnels() {

	}

	public ChampsOptionnels(int date, int position, int service, int reference,
			int progression, int programmation, int anomalie, int options) {		
		_date = date;
		_position = position;
		_service = service;
		_reference = reference;
		_progression = progression;
		_programmation = programmation;
		_anomalie = anomalie;
		_options = options;
	}

	public int getAnomalie() {
		return _anomalie;
	}

	public void setAnomalie(int anomalie) {
		_anomalie = anomalie;
	}

	public int getDate() {
		return _date;
	}

	public void setDate(int date) {
		_date = date;
	}

	public int getOptions() {
		return _options;
	}

	public void setOptions(int options) {
		_options = options;
	}

	public int getPosition() {
		return _position;
	}

	public void setPosition(int position) {
		_position = position;
	}

	public int getprogrammation() {
		return _programmation;
	}

	public void setprogrammation(int programmation) {
		_programmation = programmation;
	}

	public int getProgression() {
		return _progression;
	}

	public void setProgression(int progression) {
		_progression = progression;
	}

	public int getReference() {
		return _reference;
	}

	public void setReference(int reference) {
		_reference = reference;
	}

	public int getService() {
		return _service;
	}

	public void setService(int service) {
		_service = service;
	}

	public String toString() {
		return "[" + _date + "" + _position + "" + _service
				+ "" + _reference + "" + _progression + "" + _programmation + ""
				+ _anomalie + "" + _options + "]";
	}
	

    public int get(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _date = _F_bs.sgetbits(1);
        _position = _F_bs.sgetbits(1);
        _service = _F_bs.sgetbits(1);
        _reference = _F_bs.sgetbits(1);
        _progression = _F_bs.sgetbits(1);
        _programmation = _F_bs.sgetbits(1);
        _anomalie = _F_bs.sgetbits(1);
        _options = _F_bs.sgetbits(1);
        return _F_ret;
    }

    public int put(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _F_bs.putbits(_date, 1);
        _F_bs.putbits(_position, 1);
        _F_bs.putbits(_service, 1);
        _F_bs.putbits(_reference, 1);
        _F_bs.putbits(_progression, 1);
        _F_bs.putbits(_programmation, 1);
        _F_bs.putbits(_anomalie, 1);
        _F_bs.putbits(_options, 1);
        return _F_ret;
    }
}
