/* @flavorc
 *
 * Date.java
 * 
 * This file was automatically generated by flavorc
 * from the source file:
 *     'phoebus.fl'
 *
 * For information on flavorc, visit the Flavor Web site at:
 *     http://www.ee.columbia.edu/flavor
 *
 * -- Do not edit by hand --
 *
 */

package org.avm.business.protocol.phoebus;
import java.io.IOException;

import flavor.IBitstream;
import flavor.MapResult;

public class Date {
    int _annee;
    int _mois;
    int _jour;
    	
	public Date() {
		java.util.Calendar cal = java.util.Calendar.getInstance();
		_annee = cal.get(java.util.Calendar.YEAR) - 1990;
		_mois = cal.get(java.util.Calendar.MONTH) +1;
		_jour = cal.get(java.util.Calendar.DAY_OF_MONTH);
	}

	public Date(int _annee, int _mois, int _jour) {
		super();
		this._annee = _annee;
		this._mois = _mois;
		this._jour = _jour;
	}

	public int getAnnee() {
		return _annee;
	}

	public void setAnnee(int annee) {
		_annee = annee;
	}

	public int getJour() {
		return _jour;
	}

	public void setJour(int jour) {
		_jour = jour;
	}

	public int getMois() {
		return _mois;
	}

	public void setMois(int mois) {
		_mois = mois;
	}

	public String toString() {
		return "[" + (_annee + 1990) + "/" + _mois + "/" + _jour + "]";
	}    
	

    public int get(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _annee = _F_bs.getbits(6);
        _mois = _F_bs.getbits(4);
        _jour = _F_bs.getbits(5);
        return _F_ret;
    }

    public int put(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _F_bs.putbits(_annee, 6);
        _F_bs.putbits(_mois, 4);
        _F_bs.putbits(_jour, 5);
        return _F_ret;
    }
}
