/* @flavorc
 *
 * Horaire.java
 * 
 * This file was automatically generated by flavorc
 * from the source file:
 *     'phoebus.fl'
 *
 * For information on flavorc, visit the Flavor Web site at:
 *     http://www.ee.columbia.edu/flavor
 *
 * -- Do not edit by hand --
 *
 */

package org.avm.business.protocol.phoebus;
import java.io.IOException;

import flavor.IBitstream;
import flavor.MapResult;

public class Horaire {
    int _point;
    int _distance;
    int _arrivee;
    int _attente;
    int _girouette;
    
	public Horaire() {
		super();
    }

    public Horaire(int point, int distance, int arrivee, int attente,
	    int girouette) {
		super();
		_point = point;
		_distance = distance;
		_arrivee = arrivee;
		_attente = attente;
		_girouette = girouette;
    }

    public int getPoint() {
		return _point;
    }

    public int getDistance() {
		return _distance;
    }

    public int getArrivee() {
		return _arrivee;
    }

    public int getAttente() {
		return _attente;
    }

    public int getGirouette() {
		return _girouette;
    }

    public void setPoint(int point) {
	_point = point;
    }

    public void setDistance(int distance) {
		_distance = distance;
    }

    public void setArrivee(int arrivee) {
		_arrivee = arrivee;
    }

    public void setAttente(int attente) {
		_attente = attente;
    }

    public void setGirouette(int girouette) {
		_girouette = girouette;
    }

    public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(" [point " + _point + " distance " + _distance + " arrivee "
			+ _arrivee + " attente " + _attente + " girouette "
			+ _girouette);
		sb.append("]");
		return sb.toString();
    }
	

    public int get(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _point = _F_bs.getbits(32);
        _distance = _F_bs.getbits(24);
        _arrivee = _F_bs.sgetbits(20);
        _attente = _F_bs.sgetbits(20);
        _girouette = _F_bs.getbits(16);
        return _F_ret;
    }

    public int put(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _F_bs.putbits(_point, 32);
        _F_bs.putbits(_distance, 24);
        _F_bs.putbits(_arrivee, 20);
        _F_bs.putbits(_attente, 20);
        _F_bs.putbits(_girouette, 16);
        return _F_ret;
    }
}
