/* @flavorc
 *
 * Horodate.java
 * 
 * This file was automatically generated by flavorc
 * from the source file:
 *     'phoebus.fl'
 *
 * For information on flavorc, visit the Flavor Web site at:
 *     http://www.ee.columbia.edu/flavor
 *
 * -- Do not edit by hand --
 *
 */

package org.avm.business.protocol.phoebus;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

import flavor.Bitstream;
import flavor.IBitstream;
import flavor.MapResult;

public class Horodate {
    int _annee;
    int _mois;
    int _jour;
    int _heure;
    int _minute;
    int _seconde;
    	
	public Horodate() {
		java.util.Calendar cal = java.util.Calendar.getInstance();
		_annee = cal.get(java.util.Calendar.YEAR) - 1990;
		_mois = cal.get(java.util.Calendar.MONTH) +1 ;
		_jour = cal.get(java.util.Calendar.DAY_OF_MONTH);
		_heure = cal.get(java.util.Calendar.HOUR_OF_DAY);
		_minute = cal.get(java.util.Calendar.MINUTE);
		_seconde = cal.get(java.util.Calendar.SECOND);
	}

	public Horodate(int annee, int mois, int jour, int heure, int minute,
			int seconde) {
		super();
		_annee = annee;
		_mois = mois;
		_jour = jour;
		_heure = heure;
		_minute = minute;
		_seconde = seconde;
	}

	public int getAnnee() {
		return _annee;
	}

	public void setAnnee(int annee) {
		_annee = annee;
	}

	public int getHeure() {
		return _heure;
	}

	public void setHeure(int heure) {
		_heure = heure;
	}

	public int getJour() {
		return _jour;
	}

	public void setJour(int jour) {
		_jour = jour;
	}

	public int getMinute() {
		return _minute;
	}

	public void setMinute(int minute) {
		_minute = minute;
	}

	public int getMois() {
		return _mois;
	}

	public void setMois(int mois) {
		_mois = mois;
	}

	public int getSeconde() {
		return _seconde;
	}

	public void setSeconde(int seconde) {
		_seconde = seconde;
	}

	public String toString() {
		return "[" + (_annee + 1990) + "/" + _mois + "/" + _jour + " " + _heure
				+ ":" + _minute + ":" + _seconde + "]";
	}
	
	public byte[] toByteArray() throws IOException {
		ByteArrayOutputStream out = new ByteArrayOutputStream();
		Bitstream bs = new Bitstream(out);
		put(bs);
		bs.close();
		return out.toByteArray();
	}	
	

    public int get(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _annee = _F_bs.getbits(6);
        _mois = _F_bs.getbits(4);
        _jour = _F_bs.getbits(5);
        _heure = _F_bs.getbits(5);
        _minute = _F_bs.getbits(6);
        _seconde = _F_bs.getbits(6);
        return _F_ret;
    }

    public int put(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _F_bs.putbits(_annee, 6);
        _F_bs.putbits(_mois, 4);
        _F_bs.putbits(_jour, 5);
        _F_bs.putbits(_heure, 5);
        _F_bs.putbits(_minute, 6);
        _F_bs.putbits(_seconde, 6);
        return _F_ret;
    }
}
