/* @flavorc
 *
 * Identite.java
 * 
 * This file was automatically generated by flavorc
 * from the source file:
 *     'phoebus.fl'
 *
 * For information on flavorc, visit the Flavor Web site at:
 *     http://www.ee.columbia.edu/flavor
 *
 * -- Do not edit by hand --
 *
 */

package org.avm.business.protocol.phoebus;
import java.io.IOException;

import flavor.IBitstream;
import flavor.MapResult;

public class Identite {
    int _type;
    int _id;
    int _exploitant;
    
	public Identite() {

	}

	public Identite(int type, int id, int exploitant) {
		
		_type = type;
		_id = id;
		_exploitant = exploitant;
	}

	public int getExploitant() {
		return _exploitant;
	}

	public void setExploitant(int exploitant) {
		_exploitant = exploitant;
	}

	public int getId() {
		return _id;
	}

	public void setId(int id) {
		_id = id;
	}

	public int getType() {
		return _type;
	}

	public void setType(int type) {
		_type = type;
	}

	public String toString() {
		return "[type " + _type + " id " + _id + " exploitant " + _exploitant
				+ "]";
	}
	

    public int get(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _type = _F_bs.getbits(4);
        _id = _F_bs.getbits(17);
        _exploitant = _F_bs.getbits(11);
        return _F_ret;
    }

    public int put(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _F_bs.putbits(_type, 4);
        _F_bs.putbits(_id, 17);
        _F_bs.putbits(_exploitant, 11);
        return _F_ret;
    }
}
