/* @flavorc
 *
 * Options.java
 * 
 * This file was automatically generated by flavorc
 * from the source file:
 *     'phoebus.fl'
 *
 * For information on flavorc, visit the Flavor Web site at:
 *     http://www.ee.columbia.edu/flavor
 *
 * -- Do not edit by hand --
 *
 */

package org.avm.business.protocol.phoebus;
import java.io.IOException;

import flavor.IBitstream;
import flavor.MapResult;

public class Options {
    int _priorite;
    int _acquittement;
    
	public Options() {
		_priorite = 4;
	}

	public Options(int priorite, int acquittement) {		
		_priorite = priorite;
		_acquittement = acquittement;
	}

	public int getAcquittement() {
		return _acquittement;
	}

	public void setAcquittement(int acquittement) {
		_acquittement = acquittement;
	}

	public int getPriorite() {
		return _priorite;
	}

	public void setPriorite(int priorite) {
		_priorite = priorite;
	}

	public String toString() {
		return "[priorite " + _priorite + " acquittement " + _acquittement + "]";
	}
	

    public int get(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _priorite = _F_bs.getbits(3);
        _acquittement = _F_bs.getbits(1);
        return _F_ret;
    }

    public int put(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _F_bs.putbits(_priorite, 3);
        _F_bs.putbits(_acquittement, 1);
        return _F_ret;
    }
}
