/* @flavorc
 *
 * Position.java
 * 
 * This file was automatically generated by flavorc
 * from the source file:
 *     'phoebus.fl'
 *
 * For information on flavorc, visit the Flavor Web site at:
 *     http://www.ee.columbia.edu/flavor
 *
 * -- Do not edit by hand --
 *
 */

package org.avm.business.protocol.phoebus;
import java.io.IOException;

import flavor.IBitstream;
import flavor.MapResult;

public class Position {
    int _longitude;
    int _latitude;
    int _vitesse;
    int _cap;
    
		public Position() {		
	}

	public Position(int longitude, int latitude, int vitesse, int cap) {	
		_longitude = longitude;
		_latitude = latitude;
		_vitesse = vitesse;
		_cap = cap;
	}
	
	
	public int getCap() {
		return _cap;
	}

	public void setCap(int cap) {
		_cap = cap;
	}

	public int getLatitude() {
		return _latitude;
	}

	public void setLatitude(int latitude) {
		_latitude = latitude;
	}

	public int getLongitude() {
		return _longitude;
	}

	public void setLongitude(int longitude) {
		_longitude = longitude;
	}

	public int getVitesse() {
		return _vitesse;
	}

	public void setVitesse(int vitesse) {
		_vitesse = vitesse;
	}

	public String toString() {
		return "[longitude " + _longitude + " latitude " + _latitude + " vitesse "
				+ _vitesse + " cap " + _cap + "]";
	}
	

    public int get(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _longitude = _F_bs.sgetbits(32);
        _latitude = _F_bs.sgetbits(32);
        _vitesse = _F_bs.getbits(7);
        _cap = _F_bs.getbits(9);
        return _F_ret;
    }

    public int put(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _F_bs.putbits(_longitude, 32);
        _F_bs.putbits(_latitude, 32);
        _F_bs.putbits(_vitesse, 7);
        _F_bs.putbits(_cap, 9);
        return _F_ret;
    }
}
