/* @flavorc
 *
 * Programmation.java
 * 
 * This file was automatically generated by flavorc
 * from the source file:
 *     'phoebus.fl'
 *
 * For information on flavorc, visit the Flavor Web site at:
 *     http://www.ee.columbia.edu/flavor
 *
 * -- Do not edit by hand --
 *
 */

package org.avm.business.protocol.phoebus;
import java.io.IOException;

import flavor.IBitstream;
import flavor.MapResult;

public class Programmation {
    Date _dateDebut;
    Date _dateFin;
    int _lun;
    int _mar;
    int _mer;
    int _jeu;
    int _ven;
    int _sam;
    int _dim;
    Heure _heureDebut;
    Heure _heureFin;
    int _periode;
    
	public Programmation() {
		_dateDebut = new Date();
		_dateFin = new Date();
		_lun = _mar = _mer = _jeu = _ven = _sam = _dim = 1;
		_heureDebut = new Heure();
		_heureFin = new Heure();
		_periode = 60;
	}

	public Programmation(Date dateDebut, Date dateFin, int lun, int mar,
			int mer, int jeu, int ven, int sam, int dim, Heure heureDebut,
			Heure heureFin, int periode) {
		super();
		_dateDebut = dateDebut;
		_dateFin = dateFin;
		_lun = lun;
		_mar = mar;
		_mer = mer;
		_jeu = jeu;
		_ven = ven;
		_sam = sam;
		_dim = dim;
		_heureDebut = heureDebut;
		_heureFin = heureFin;
		_periode = periode;
	}

	public Date getDateDebut() {
		return _dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		_dateDebut = dateDebut;
	}

	public Date getDateFin() {
		return _dateFin;
	}

	public void setDateFin(Date dateFin) {
		_dateFin = dateFin;
	}

	public int getDim() {
		return _dim;
	}

	public void setDim(int dim) {
		_dim = dim;
	}

	public Heure getHeureDebut() {
		return _heureDebut;
	}

	public void setHeureDebut(Heure heureDebut) {
		_heureDebut = heureDebut;
	}

	public Heure getHeureFin() {
		return _heureFin;
	}

	public void setHeureFin(Heure heureFin) {
		_heureFin = heureFin;
	}

	public int getJeu() {
		return _jeu;
	}

	public void setJeu(int jeu) {
		_jeu = jeu;
	}

	public int getLun() {
		return _lun;
	}

	public void setLun(int lun) {
		_lun = lun;
	}

	public int getMar() {
		return _mar;
	}

	public void setMar(int mar) {
		_mar = mar;
	}

	public int getMer() {
		return _mer;
	}

	public void setMer(int mer) {
		_mer = mer;
	}

	public int getPeriode() {
		return _periode;
	}

	public void setPeriode(int periode) {
		_periode = periode;
	}

	public int getSam() {
		return _sam;
	}

	public void setSam(int sam) {
		_sam = sam;
	}

	public int getVen() {
		return _ven;
	}

	public void setVen(int ven) {
		_ven = ven;
	}

	public String toString() {
		return "[date debut: " + _dateDebut + " date fin: " + _dateFin
				+ " jour de la semaine " + _lun + "" + _mar + "" + _mer + ""
				+ _jeu + "" + _ven + "" + _sam + "" + _dim + " heure debut: "
				+ _heureDebut + " heure fin: " + _heureFin + " periode "
				+ _periode + "]";
	}
	

    public int get(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _dateDebut = new Date();
        _F_ret += _dateDebut.get(_F_bs);
        _dateFin = new Date();
        _F_ret += _dateFin.get(_F_bs);
        _lun = _F_bs.getbits(1);
        _mar = _F_bs.getbits(1);
        _mer = _F_bs.getbits(1);
        _jeu = _F_bs.getbits(1);
        _ven = _F_bs.getbits(1);
        _sam = _F_bs.getbits(1);
        _dim = _F_bs.getbits(1);
        _heureDebut = new Heure();
        _F_ret += _heureDebut.get(_F_bs);
        _heureFin = new Heure();
        _F_ret += _heureFin.get(_F_bs);
        _periode = _F_bs.getbits(17);
        return _F_ret;
    }

    public int put(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _F_ret += _dateDebut.put(_F_bs);
        _F_ret += _dateFin.put(_F_bs);
        _F_bs.putbits(_lun, 1);
        _F_bs.putbits(_mar, 1);
        _F_bs.putbits(_mer, 1);
        _F_bs.putbits(_jeu, 1);
        _F_bs.putbits(_ven, 1);
        _F_bs.putbits(_sam, 1);
        _F_bs.putbits(_dim, 1);
        _F_ret += _heureDebut.put(_F_bs);
        _F_ret += _heureFin.put(_F_bs);
        _F_bs.putbits(_periode, 17);
        return _F_ret;
    }
}
