/* @flavorc
 *
 * Progression.java
 * 
 * This file was automatically generated by flavorc
 * from the source file:
 *     'phoebus.fl'
 *
 * For information on flavorc, visit the Flavor Web site at:
 *     http://www.ee.columbia.edu/flavor
 *
 * -- Do not edit by hand --
 *
 */

package org.avm.business.protocol.phoebus;
import java.io.IOException;

import flavor.IBitstream;
import flavor.MapResult;

public class Progression {
    int _avanceRetard;
    int _iduDernierArret;
    int _rangDernierArret;
    int _progression;
    int _deviation;
    
	public Progression(){
    	
    }
    
    public Progression(int retard, int iduDernierArret, int rangDernierArret, int progression, int deviation) {
		_avanceRetard = retard;
		_iduDernierArret	= iduDernierArret;
		_rangDernierArret = rangDernierArret;
		_progression = progression;
		_deviation = deviation;
	}

	public int getDeviation() {
		return _deviation;
	}

	public void setDeviation(int deviation) {
		_deviation = deviation;
	}

	public int getProgression() {
		return _progression;
	}

	public void setProgression(int progression) {
		_progression = progression;
	}

	public int getIduDernierArret() {
		return _iduDernierArret;
	}

	public int getRangDernierArret() {
		return _rangDernierArret;
	}

	public void setIduDernierArret(int iduDernierArret) {
		_iduDernierArret = iduDernierArret;
	}	
	
	public void setRangDernierArret(int rangDernierArret) {
		_rangDernierArret = rangDernierArret;
	}

	public int getRetard() {
		return _avanceRetard;
	}

	public void setRetard(int retard) {
		_avanceRetard = retard;
	}
	
	public String toString() {
		return "[retard " + _avanceRetard + " rang dernier arret " + _rangDernierArret + " idu dernier arret " + _iduDernierArret
		+ " progression " + _progression + " deviation " + _deviation + "]";
	}
	

    public int get(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _avanceRetard = _F_bs.sgetbits(16);
        _iduDernierArret = _F_bs.getbits(32);
        _rangDernierArret = _F_bs.getbits(8);
        _progression = _F_bs.getbits(7);
        _deviation = _F_bs.getbits(1);
        return _F_ret;
    }

    public int put(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _F_bs.putbits(_avanceRetard, 16);
        _F_bs.putbits(_iduDernierArret, 32);
        _F_bs.putbits(_rangDernierArret, 8);
        _F_bs.putbits(_progression, 7);
        _F_bs.putbits(_deviation, 1);
        return _F_ret;
    }
}
