/* @flavorc
 *
 * Reference.java
 * 
 * This file was automatically generated by flavorc
 * from the source file:
 *     'phoebus.fl'
 *
 * For information on flavorc, visit the Flavor Web site at:
 *     http://www.ee.columbia.edu/flavor
 *
 * -- Do not edit by hand --
 *
 */

package org.avm.business.protocol.phoebus;
import java.io.IOException;

import flavor.IBitstream;
import flavor.MapResult;

public class Reference {
    long _id;
    int _acquittement;
    int _annulation;
    
	public Reference() {

	}

	public Reference(long id, int acquittement, int annulation) {
		super();
		_id = id;
		_acquittement = acquittement;
		_annulation = annulation;
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public int getAcquittement() {
		return _acquittement;
	}

	public void setAcquittement(int acquittement) {
		_acquittement = acquittement;
	}

	public int getAnnulation() {
		return _annulation;
	}

	public void setAnnulation(int annulation) {
		_annulation = annulation;
	}

	public String toString() {
		return "[id " + _id + " acquittement "+ _acquittement + " annulation " + _annulation +"]";
	}
	

    public int get(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _id = _F_bs.getlong(40);
        _acquittement = _F_bs.getbits(1);
        _annulation = _F_bs.getbits(1);
        return _F_ret;
    }

    public int put(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        _F_bs.putlong(_id, 40);
        _F_bs.putbits(_acquittement, 1);
        _F_bs.putbits(_annulation, 1);
        return _F_ret;
    }
}
