/* @flavorc
 *
 * Varchar.java
 * 
 * This file was automatically generated by flavorc
 * from the source file:
 *     'phoebus.fl'
 *
 * For information on flavorc, visit the Flavor Web site at:
 *     http://www.ee.columbia.edu/flavor
 *
 * -- Do not edit by hand --
 *
 */

package org.avm.business.protocol.phoebus;
import java.io.IOException;

import flavor.IBitstream;
import flavor.MapResult;

public class Varchar {
    int _longueur;
    char _value[] = new char[256];
    
	public Varchar() {
		this("");
	}

	public Varchar(String value) {
		setValue(value);
	}
	
	public String getValue() {
		return new String(_value).substring(0, _longueur);	
	}
	
	public void setValue(String value) {
		char[] tmp = value.toCharArray();		
		System.arraycopy(tmp, 0, _value, 0, tmp.length );		
		_longueur = tmp.length;
	}
	
	public String toString() {
		return getValue();
	}
	

    public int get(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        int _F_dim0, _F_dim0_end;
        _longueur = _F_bs.sgetbits(8);
        _F_dim0_end = _longueur;
        for (_F_dim0 = 0; _F_dim0 < _F_dim0_end; _F_dim0++) {
            _value[_F_dim0] = (char) _F_bs.getbits(8);
        }
        return _F_ret;
    }

    public int put(IBitstream _F_bs) throws IOException {
        int _F_ret = 0;
        MapResult _F_mr;
        int _F_dim0, _F_dim0_end;
        _F_bs.putbits(_longueur, 8);
        _F_dim0_end = _longueur;
        for (_F_dim0 = 0; _F_dim0 < _F_dim0_end; _F_dim0++) {
            _F_bs.putbits(_value[_F_dim0], 8);
        }
        return _F_ret;
    }
}
