/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_avm_device_protocol_vcan_Connection */

#ifndef _Included_org_avm_device_protocol_vcan_Connection
#define _Included_org_avm_device_protocol_vcan_Connection
#ifdef __cplusplus
extern "C" {
#endif
#undef org_avm_device_protocol_vcan_Connection_READ
#define org_avm_device_protocol_vcan_Connection_READ 1L
#undef org_avm_device_protocol_vcan_Connection_WRITE
#define org_avm_device_protocol_vcan_Connection_WRITE 2L
#undef org_avm_device_protocol_vcan_Connection_READ_WRITE
#define org_avm_device_protocol_vcan_Connection_READ_WRITE 3L
#undef org_avm_device_protocol_vcan_Connection_DEFAULT_TIMEOUT
#define org_avm_device_protocol_vcan_Connection_DEFAULT_TIMEOUT 100L
#undef org_avm_device_protocol_vcan_Connection_DEFAULT_BAUDRATE
#define org_avm_device_protocol_vcan_Connection_DEFAULT_BAUDRATE 125000L
#undef org_avm_device_protocol_vcan_Connection_UNOPENED
#define org_avm_device_protocol_vcan_Connection_UNOPENED 0L
#undef org_avm_device_protocol_vcan_Connection_OPENED
#define org_avm_device_protocol_vcan_Connection_OPENED 1L
#undef org_avm_device_protocol_vcan_Connection_CLOSED
#define org_avm_device_protocol_vcan_Connection_CLOSED 2L
#undef org_avm_device_protocol_vcan_Connection_FRAME_LEN
#define org_avm_device_protocol_vcan_Connection_FRAME_LEN 14L
/*
 * Class:     org_avm_device_protocol_vcan_Connection
 * Method:    openImpl
 * Signature: (III[I[I)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_protocol_vcan_Connection_openImpl
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jintArray);

/*
 * Class:     org_avm_device_protocol_vcan_Connection
 * Method:    closeImpl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_avm_device_protocol_vcan_Connection_closeImpl
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_avm_device_protocol_vcan_Connection
 * Method:    readImpl
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_protocol_vcan_Connection_readImpl
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     org_avm_device_protocol_vcan_Connection
 * Method:    writeImpl
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_protocol_vcan_Connection_writeImpl
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     org_avm_device_protocol_vcan_Connection
 * Method:    availableImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_protocol_vcan_Connection_availableImpl
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
