/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package org.avm.device.fm6000.ac97.jni;

public interface COMVS_AC97Constants {

	public final static int COMVS_TRUE = COMVS_AC97JNI.COMVS_TRUE_get();
	public final static int COMVS_FALSE = COMVS_AC97JNI.COMVS_FALSE_get();
}
