/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package org.avm.device.fm6000.ac97.jni;

public class COMVS_AC97 implements COMVS_AC97Constants {

	public static short Comvs_Mute_out_Master(short arg0) {
		return COMVS_AC97JNI.Comvs_Mute_out_Master(arg0);
	}

	public static short Comvs_Mute_out_HeadPhone(short arg0) {
		return COMVS_AC97JNI.Comvs_Mute_out_HeadPhone(arg0);
	}

	public static short Comvs_Mute_out_MonoOut(short arg0) {
		return COMVS_AC97JNI.Comvs_Mute_out_MonoOut(arg0);
	}

	public static short Comvs_Mute_in_Beep(short arg0) {
		return COMVS_AC97JNI.Comvs_Mute_in_Beep(arg0);
	}

	public static short Comvs_Mute_in_Phone(short arg0) {
		return COMVS_AC97JNI.Comvs_Mute_in_Phone(arg0);
	}

	public static short Comvs_Mute_in_Microphone(short arg0) {
		return COMVS_AC97JNI.Comvs_Mute_in_Microphone(arg0);
	}

	public static short Comvs_Mute_in_LineIn(short arg0) {
		return COMVS_AC97JNI.Comvs_Mute_in_LineIn(arg0);
	}

	public static short Comvs_Mute_in_CD(short arg0) {
		return COMVS_AC97JNI.Comvs_Mute_in_CD(arg0);
	}

	public static short Comvs_Mute_in_Video(short arg0) {
		return COMVS_AC97JNI.Comvs_Mute_in_Video(arg0);
	}

	public static short Comvs_Mute_in_Aux(short arg0) {
		return COMVS_AC97JNI.Comvs_Mute_in_Aux(arg0);
	}

	public static short Comvs_Mute_in_PCM(short arg0) {
		return COMVS_AC97JNI.Comvs_Mute_in_PCM(arg0);
	}

	public static short Comvs_Is_Mute_out_Master(short[] arg0) {
		return COMVS_AC97JNI.Comvs_Is_Mute_out_Master(arg0);
	}

	public static short Comvs_Is_Mute_out_HeadPhone(short[] arg0) {
		return COMVS_AC97JNI.Comvs_Is_Mute_out_HeadPhone(arg0);
	}

	public static short Comvs_Is_Mute_out_MonoOut(short[] arg0) {
		return COMVS_AC97JNI.Comvs_Is_Mute_out_MonoOut(arg0);
	}

	public static short Comvs_Is_Mute_in_Beep(short[] arg0) {
		return COMVS_AC97JNI.Comvs_Is_Mute_in_Beep(arg0);
	}

	public static short Comvs_Is_Mute_in_Phone(short[] arg0) {
		return COMVS_AC97JNI.Comvs_Is_Mute_in_Phone(arg0);
	}

	public static short Comvs_Is_Mute_in_Microphone(short[] arg0) {
		return COMVS_AC97JNI.Comvs_Is_Mute_in_Microphone(arg0);
	}

	public static short Comvs_Is_Mute_in_LineIn(short[] arg0) {
		return COMVS_AC97JNI.Comvs_Is_Mute_in_LineIn(arg0);
	}

	public static short Comvs_Is_Mute_in_CD(short[] arg0) {
		return COMVS_AC97JNI.Comvs_Is_Mute_in_CD(arg0);
	}

	public static short Comvs_Is_Mute_in_Video(short[] arg0) {
		return COMVS_AC97JNI.Comvs_Is_Mute_in_Video(arg0);
	}

	public static short Comvs_Is_Mute_in_Aux(short[] arg0) {
		return COMVS_AC97JNI.Comvs_Is_Mute_in_Aux(arg0);
	}

	public static short Comvs_Is_Mute_in_PCM(short[] arg0) {
		return COMVS_AC97JNI.Comvs_Is_Mute_in_PCM(arg0);
	}

	public static short Comvs_GetGain_out_Master(short[] arg0, short[] arg1) {
		return COMVS_AC97JNI.Comvs_GetGain_out_Master(arg0, arg1);
	}

	public static short Comvs_GetGain_out_HeadPhone(short[] arg0, short[] arg1) {
		return COMVS_AC97JNI.Comvs_GetGain_out_HeadPhone(arg0, arg1);
	}

	public static short Comvs_GetGain_out_MonoOut(short[] arg0) {
		return COMVS_AC97JNI.Comvs_GetGain_out_MonoOut(arg0);
	}

	public static short Comvs_GetGain_in_Beep(short[] arg0) {
		return COMVS_AC97JNI.Comvs_GetGain_in_Beep(arg0);
	}

	public static short Comvs_GetGain_in_Phone(short[] arg0) {
		return COMVS_AC97JNI.Comvs_GetGain_in_Phone(arg0);
	}

	public static short Comvs_GetGain_in_Microphone(short[] arg0) {
		return COMVS_AC97JNI.Comvs_GetGain_in_Microphone(arg0);
	}

	public static short Comvs_GetGain_in_LineIn(short[] arg0, short[] arg1) {
		return COMVS_AC97JNI.Comvs_GetGain_in_LineIn(arg0, arg1);
	}

	public static short Comvs_GetGain_in_CD(short[] arg0, short[] arg1) {
		return COMVS_AC97JNI.Comvs_GetGain_in_CD(arg0, arg1);
	}

	public static short Comvs_GetGain_in_Video(short[] arg0, short[] arg1) {
		return COMVS_AC97JNI.Comvs_GetGain_in_Video(arg0, arg1);
	}

	public static short Comvs_GetGain_in_Aux(short[] arg0, short[] arg1) {
		return COMVS_AC97JNI.Comvs_GetGain_in_Aux(arg0, arg1);
	}

	public static short Comvs_GetGain_in_PCM(short[] arg0, short[] arg1) {
		return COMVS_AC97JNI.Comvs_GetGain_in_PCM(arg0, arg1);
	}

	public static short Comvs_SetGain_out_Master(short arg0, short arg1) {
		return COMVS_AC97JNI.Comvs_SetGain_out_Master(arg0, arg1);
	}

	public static short Comvs_SetGain_out_HeadPhone(short arg0, short arg1) {
		return COMVS_AC97JNI.Comvs_SetGain_out_HeadPhone(arg0, arg1);
	}

	public static short Comvs_SetGain_out_MonoOut(short arg0) {
		return COMVS_AC97JNI.Comvs_SetGain_out_MonoOut(arg0);
	}

	public static short Comvs_SetGain_in_Beep(short arg0) {
		return COMVS_AC97JNI.Comvs_SetGain_in_Beep(arg0);
	}

	public static short Comvs_SetGain_in_Phone(short arg0) {
		return COMVS_AC97JNI.Comvs_SetGain_in_Phone(arg0);
	}

	public static short Comvs_SetGain_in_Microphone(short arg0) {
		return COMVS_AC97JNI.Comvs_SetGain_in_Microphone(arg0);
	}

	public static short Comvs_SetGain_in_LineIn(short arg0, short arg1) {
		return COMVS_AC97JNI.Comvs_SetGain_in_LineIn(arg0, arg1);
	}

	public static short Comvs_SetGain_in_CD(short arg0, short arg1) {
		return COMVS_AC97JNI.Comvs_SetGain_in_CD(arg0, arg1);
	}

	public static short Comvs_SetGain_in_Video(short arg0, short arg1) {
		return COMVS_AC97JNI.Comvs_SetGain_in_Video(arg0, arg1);
	}

	public static short Comvs_SetGain_in_Aux(short arg0, short arg1) {
		return COMVS_AC97JNI.Comvs_SetGain_in_Aux(arg0, arg1);
	}

	public static short Comvs_SetGain_in_PCM(short arg0, short arg1) {
		return COMVS_AC97JNI.Comvs_SetGain_in_PCM(arg0, arg1);
	}

	public static short Comvs_SetExtraGain_in_Microphone(short arg0) {
		return COMVS_AC97JNI.Comvs_SetExtraGain_in_Microphone(arg0);
	}

	public static short Comvs_GetExtraGain_in_Microphone(short[] arg0) {
		return COMVS_AC97JNI.Comvs_GetExtraGain_in_Microphone(arg0);
	}

	public static short Comvs_SetMicro_MonoOut(short arg0) {
		return COMVS_AC97JNI.Comvs_SetMicro_MonoOut(arg0);
	}

	public static short Comvs_GetMicro_MonoOut(short[] arg0) {
		return COMVS_AC97JNI.Comvs_GetMicro_MonoOut(arg0);
	}
}
