/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package org.avm.device.fm6000.ac97.jni;

class COMVS_AC97JNI {

	static {
		try {
			System.loadLibrary("comvs_ac97");
		} catch (UnsatisfiedLinkError e) {
			System.err.println("Native code library failed to load. \n" + e);
		}
	}

	public final static native int COMVS_TRUE_get();

	public final static native int COMVS_FALSE_get();

	public final static native short Comvs_Mute_out_Master(short jarg1);

	public final static native short Comvs_Mute_out_HeadPhone(short jarg1);

	public final static native short Comvs_Mute_out_MonoOut(short jarg1);

	public final static native short Comvs_Mute_in_Beep(short jarg1);

	public final static native short Comvs_Mute_in_Phone(short jarg1);

	public final static native short Comvs_Mute_in_Microphone(short jarg1);

	public final static native short Comvs_Mute_in_LineIn(short jarg1);

	public final static native short Comvs_Mute_in_CD(short jarg1);

	public final static native short Comvs_Mute_in_Video(short jarg1);

	public final static native short Comvs_Mute_in_Aux(short jarg1);

	public final static native short Comvs_Mute_in_PCM(short jarg1);

	public final static native short Comvs_Is_Mute_out_Master(short[] jarg1);

	public final static native short Comvs_Is_Mute_out_HeadPhone(short[] jarg1);

	public final static native short Comvs_Is_Mute_out_MonoOut(short[] jarg1);

	public final static native short Comvs_Is_Mute_in_Beep(short[] jarg1);

	public final static native short Comvs_Is_Mute_in_Phone(short[] jarg1);

	public final static native short Comvs_Is_Mute_in_Microphone(short[] jarg1);

	public final static native short Comvs_Is_Mute_in_LineIn(short[] jarg1);

	public final static native short Comvs_Is_Mute_in_CD(short[] jarg1);

	public final static native short Comvs_Is_Mute_in_Video(short[] jarg1);

	public final static native short Comvs_Is_Mute_in_Aux(short[] jarg1);

	public final static native short Comvs_Is_Mute_in_PCM(short[] jarg1);

	public final static native short Comvs_GetGain_out_Master(short[] jarg1,
			short[] jarg2);

	public final static native short Comvs_GetGain_out_HeadPhone(short[] jarg1,
			short[] jarg2);

	public final static native short Comvs_GetGain_out_MonoOut(short[] jarg1);

	public final static native short Comvs_GetGain_in_Beep(short[] jarg1);

	public final static native short Comvs_GetGain_in_Phone(short[] jarg1);

	public final static native short Comvs_GetGain_in_Microphone(short[] jarg1);

	public final static native short Comvs_GetGain_in_LineIn(short[] jarg1,
			short[] jarg2);

	public final static native short Comvs_GetGain_in_CD(short[] jarg1,
			short[] jarg2);

	public final static native short Comvs_GetGain_in_Video(short[] jarg1,
			short[] jarg2);

	public final static native short Comvs_GetGain_in_Aux(short[] jarg1,
			short[] jarg2);

	public final static native short Comvs_GetGain_in_PCM(short[] jarg1,
			short[] jarg2);

	public final static native short Comvs_SetGain_out_Master(short jarg1,
			short jarg2);

	public final static native short Comvs_SetGain_out_HeadPhone(short jarg1,
			short jarg2);

	public final static native short Comvs_SetGain_out_MonoOut(short jarg1);

	public final static native short Comvs_SetGain_in_Beep(short jarg1);

	public final static native short Comvs_SetGain_in_Phone(short jarg1);

	public final static native short Comvs_SetGain_in_Microphone(short jarg1);

	public final static native short Comvs_SetGain_in_LineIn(short jarg1,
			short jarg2);

	public final static native short Comvs_SetGain_in_CD(short jarg1,
			short jarg2);

	public final static native short Comvs_SetGain_in_Video(short jarg1,
			short jarg2);

	public final static native short Comvs_SetGain_in_Aux(short jarg1,
			short jarg2);

	public final static native short Comvs_SetGain_in_PCM(short jarg1,
			short jarg2);

	public final static native short Comvs_SetExtraGain_in_Microphone(
			short jarg1);

	public final static native short Comvs_GetExtraGain_in_Microphone(
			short[] jarg1);

	public final static native short Comvs_SetMicro_MonoOut(short jarg1);

	public final static native short Comvs_GetMicro_MonoOut(short[] jarg1);
}
