/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_avm_device_vtc1010_common_NexcomDriverAccess */

#ifndef _Included_org_avm_device_vtc1010_common_NexcomDriverAccess
#define _Included_org_avm_device_vtc1010_common_NexcomDriverAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_avm_device_vtc1010_common_NexcomDriverAccess
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_vtc1010_common_NexcomDriverAccess_open
  (JNIEnv *, jclass);

/*
 * Class:     org_avm_device_vtc1010_common_NexcomDriverAccess
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_avm_device_vtc1010_common_NexcomDriverAccess_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_avm_device_vtc1010_common_NexcomDriverAccess
 * Method:    readInput
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_vtc1010_common_NexcomDriverAccess_readInput
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_avm_device_vtc1010_common_NexcomDriverAccess
 * Method:    setOutput
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_avm_device_vtc1010_common_NexcomDriverAccess_setOutput
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_avm_device_vtc1010_common_NexcomDriverAccess
 * Method:    readConfig
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_vtc1010_common_NexcomDriverAccess_readConfig
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_avm_device_vtc1010_common_NexcomDriverAccess
 * Method:    writeConfig
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_avm_device_vtc1010_common_NexcomDriverAccess_writeConfig
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
