/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.fm6000.wifi.jni;

public final class COMVS_WIFI_STATUS {
  public final static COMVS_WIFI_STATUS SUCCESS = new COMVS_WIFI_STATUS("SUCCESS", COMVS_WIFIJNI.SUCCESS_get());
  public final static COMVS_WIFI_STATUS ERR_WIFI_NO_CARD = new COMVS_WIFI_STATUS("ERR_WIFI_NO_CARD", COMVS_WIFIJNI.ERR_WIFI_NO_CARD_get());
  public final static COMVS_WIFI_STATUS ERR_WIFI_NO_INTERF = new COMVS_WIFI_STATUS("ERR_WIFI_NO_INTERF", COMVS_WIFIJNI.ERR_WIFI_NO_INTERF_get());
  public final static COMVS_WIFI_STATUS ERR_WIFI_NO_CONFIG = new COMVS_WIFI_STATUS("ERR_WIFI_NO_CONFIG", COMVS_WIFIJNI.ERR_WIFI_NO_CONFIG_get());
  public final static COMVS_WIFI_STATUS ERR_WIFI_BAD_SSID = new COMVS_WIFI_STATUS("ERR_WIFI_BAD_SSID", COMVS_WIFIJNI.ERR_WIFI_BAD_SSID_get());
  public final static COMVS_WIFI_STATUS ERR_WIFI_SIZE_DATA = new COMVS_WIFI_STATUS("ERR_WIFI_SIZE_DATA", COMVS_WIFIJNI.ERR_WIFI_SIZE_DATA_get());
  public final static COMVS_WIFI_STATUS ERR_WIFI_BAD_POINTER = new COMVS_WIFI_STATUS("ERR_WIFI_BAD_POINTER", COMVS_WIFIJNI.ERR_WIFI_BAD_POINTER_get());
  public final static COMVS_WIFI_STATUS ERR_WIFI = new COMVS_WIFI_STATUS("ERR_WIFI", COMVS_WIFIJNI.ERR_WIFI_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static COMVS_WIFI_STATUS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + COMVS_WIFI_STATUS.class + " with value " + swigValue);
  }

  private COMVS_WIFI_STATUS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private COMVS_WIFI_STATUS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private COMVS_WIFI_STATUS(String swigName, COMVS_WIFI_STATUS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static COMVS_WIFI_STATUS[] swigValues = { SUCCESS, ERR_WIFI_NO_CARD, ERR_WIFI_NO_INTERF, ERR_WIFI_NO_CONFIG, ERR_WIFI_BAD_SSID, ERR_WIFI_SIZE_DATA, ERR_WIFI_BAD_POINTER, ERR_WIFI };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

