/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.fm6000.wifi.jni;

public class COMVS_WIFIDEVICE_WEP_CONFIGURATION {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected COMVS_WIFIDEVICE_WEP_CONFIGURATION(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(COMVS_WIFIDEVICE_WEP_CONFIGURATION obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			COMVS_WIFIJNI.delete_COMVS_WIFIDEVICE_WEP_CONFIGURATION(swigCPtr);
		}
		swigCPtr = 0;
	}

	public void setUlWEP_key_index(long value) {
		COMVS_WIFIJNI.COMVS_WIFIDEVICE_WEP_CONFIGURATION_ulWEP_key_index_set(
				swigCPtr, this, value);
	}

	public long getUlWEP_key_index() {
		return COMVS_WIFIJNI
				.COMVS_WIFIDEVICE_WEP_CONFIGURATION_ulWEP_key_index_get(
						swigCPtr, this);
	}

	public void setUlWEP_key_size(long value) {
		COMVS_WIFIJNI.COMVS_WIFIDEVICE_WEP_CONFIGURATION_ulWEP_key_size_set(
				swigCPtr, this, value);
	}

	public long getUlWEP_key_size() {
		return COMVS_WIFIJNI
				.COMVS_WIFIDEVICE_WEP_CONFIGURATION_ulWEP_key_size_get(
						swigCPtr, this);
	}

	public void setUcWEP_key(String value) {
		COMVS_WIFIJNI.COMVS_WIFIDEVICE_WEP_CONFIGURATION_ucWEP_key_set(
				swigCPtr, this, value);
	}

	public String getUcWEP_key() {
		return COMVS_WIFIJNI.COMVS_WIFIDEVICE_WEP_CONFIGURATION_ucWEP_key_get(
				swigCPtr, this);
	}

	public void setReserved(SWIGTYPE_p_void value) {
		COMVS_WIFIJNI.COMVS_WIFIDEVICE_WEP_CONFIGURATION_reserved_set(swigCPtr,
				this, SWIGTYPE_p_void.getCPtr(value));
	}

	public SWIGTYPE_p_void getReserved() {
		long cPtr = COMVS_WIFIJNI
				.COMVS_WIFIDEVICE_WEP_CONFIGURATION_reserved_get(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
	}

	public COMVS_WIFIDEVICE_WEP_CONFIGURATION() {
		this(COMVS_WIFIJNI.new_COMVS_WIFIDEVICE_WEP_CONFIGURATION(), true);
	}

}
