/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.fm6000.wifi.jni;

public class COMVS_WIFIDEVICE_EAPOL_PARAMS {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected COMVS_WIFIDEVICE_EAPOL_PARAMS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(COMVS_WIFIDEVICE_EAPOL_PARAMS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      COMVS_WIFIJNI.delete_COMVS_WIFIDEVICE_EAPOL_PARAMS(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setIEnable8021x(int value) {
    COMVS_WIFIJNI.COMVS_WIFIDEVICE_EAPOL_PARAMS_iEnable8021x_set(swigCPtr, this, value);
  }

  public int getIEnable8021x() {
    return COMVS_WIFIJNI.COMVS_WIFIDEVICE_EAPOL_PARAMS_iEnable8021x_get(swigCPtr, this);
  }

  public void setUlEapFlags(long value) {
    COMVS_WIFIJNI.COMVS_WIFIDEVICE_EAPOL_PARAMS_ulEapFlags_set(swigCPtr, this, value);
  }

  public long getUlEapFlags() {
    return COMVS_WIFIJNI.COMVS_WIFIDEVICE_EAPOL_PARAMS_ulEapFlags_get(swigCPtr, this);
  }

  public void setUlEapType(long value) {
    COMVS_WIFIJNI.COMVS_WIFIDEVICE_EAPOL_PARAMS_ulEapType_set(swigCPtr, this, value);
  }

  public long getUlEapType() {
    return COMVS_WIFIJNI.COMVS_WIFIDEVICE_EAPOL_PARAMS_ulEapType_get(swigCPtr, this);
  }

  public void setUlAuthDataLen(long value) {
    COMVS_WIFIJNI.COMVS_WIFIDEVICE_EAPOL_PARAMS_ulAuthDataLen_set(swigCPtr, this, value);
  }

  public long getUlAuthDataLen() {
    return COMVS_WIFIJNI.COMVS_WIFIDEVICE_EAPOL_PARAMS_ulAuthDataLen_get(swigCPtr, this);
  }

  public void setPucAuthData(String value) {
    COMVS_WIFIJNI.COMVS_WIFIDEVICE_EAPOL_PARAMS_pucAuthData_set(swigCPtr, this, value);
  }

  public String getPucAuthData() {
    return COMVS_WIFIJNI.COMVS_WIFIDEVICE_EAPOL_PARAMS_pucAuthData_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_void value) {
    COMVS_WIFIJNI.COMVS_WIFIDEVICE_EAPOL_PARAMS_reserved_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getReserved() {
    long cPtr = COMVS_WIFIJNI.COMVS_WIFIDEVICE_EAPOL_PARAMS_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public COMVS_WIFIDEVICE_EAPOL_PARAMS() {
    this(COMVS_WIFIJNI.new_COMVS_WIFIDEVICE_EAPOL_PARAMS(), true);
  }

}
