/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.fm6000.wifi.jni;

public interface COMVS_WIFIConstants {
	public final static int COMVS_TRUE = COMVS_WIFIJNI.COMVS_TRUE_get();
	public final static int COMVS_FALSE = COMVS_WIFIJNI.COMVS_FALSE_get();
	public final static int WEP_KEY_SIZE_MAX = COMVS_WIFIJNI
			.WEP_KEY_SIZE_MAX_get();
	public final static int SSID_SIZE_MAX = COMVS_WIFIJNI.SSID_SIZE_MAX_get();
	public final static int MAC_SIZE = COMVS_WIFIJNI.MAC_SIZE_get();
}
