/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.fm6000.wifi.jni;

class COMVS_WIFIJNI {

	static {
		try {
			System.loadLibrary("comvs_wifi");
		} catch (UnsatisfiedLinkError e) {
			System.err.println("Native code library failed to load. \n" + e);
		}
	}

	public final static native int COMVS_TRUE_get();

	public final static native int COMVS_FALSE_get();

	public final static native int WEP_KEY_SIZE_MAX_get();

	public final static native int SSID_SIZE_MAX_get();

	public final static native int MAC_SIZE_get();

	public final static native int SUCCESS_get();

	public final static native int ERR_WIFI_NO_CARD_get();

	public final static native int ERR_WIFI_NO_INTERF_get();

	public final static native int ERR_WIFI_NO_CONFIG_get();

	public final static native int ERR_WIFI_BAD_SSID_get();

	public final static native int ERR_WIFI_SIZE_DATA_get();

	public final static native int ERR_WIFI_BAD_POINTER_get();

	public final static native int ERR_WIFI_get();

	public final static native void COMVS_WIFIDEVICE_EAPOL_PARAMS_iEnable8021x_set(
			long jarg1, COMVS_WIFIDEVICE_EAPOL_PARAMS jarg1_, int jarg2);

	public final static native int COMVS_WIFIDEVICE_EAPOL_PARAMS_iEnable8021x_get(
			long jarg1, COMVS_WIFIDEVICE_EAPOL_PARAMS jarg1_);

	public final static native void COMVS_WIFIDEVICE_EAPOL_PARAMS_ulEapFlags_set(
			long jarg1, COMVS_WIFIDEVICE_EAPOL_PARAMS jarg1_, long jarg2);

	public final static native long COMVS_WIFIDEVICE_EAPOL_PARAMS_ulEapFlags_get(
			long jarg1, COMVS_WIFIDEVICE_EAPOL_PARAMS jarg1_);

	public final static native void COMVS_WIFIDEVICE_EAPOL_PARAMS_ulEapType_set(
			long jarg1, COMVS_WIFIDEVICE_EAPOL_PARAMS jarg1_, long jarg2);

	public final static native long COMVS_WIFIDEVICE_EAPOL_PARAMS_ulEapType_get(
			long jarg1, COMVS_WIFIDEVICE_EAPOL_PARAMS jarg1_);

	public final static native void COMVS_WIFIDEVICE_EAPOL_PARAMS_ulAuthDataLen_set(
			long jarg1, COMVS_WIFIDEVICE_EAPOL_PARAMS jarg1_, long jarg2);

	public final static native long COMVS_WIFIDEVICE_EAPOL_PARAMS_ulAuthDataLen_get(
			long jarg1, COMVS_WIFIDEVICE_EAPOL_PARAMS jarg1_);

	public final static native void COMVS_WIFIDEVICE_EAPOL_PARAMS_pucAuthData_set(
			long jarg1, COMVS_WIFIDEVICE_EAPOL_PARAMS jarg1_, String jarg2);

	public final static native String COMVS_WIFIDEVICE_EAPOL_PARAMS_pucAuthData_get(
			long jarg1, COMVS_WIFIDEVICE_EAPOL_PARAMS jarg1_);

	public final static native void COMVS_WIFIDEVICE_EAPOL_PARAMS_reserved_set(
			long jarg1, COMVS_WIFIDEVICE_EAPOL_PARAMS jarg1_, long jarg2);

	public final static native long COMVS_WIFIDEVICE_EAPOL_PARAMS_reserved_get(
			long jarg1, COMVS_WIFIDEVICE_EAPOL_PARAMS jarg1_);

	public final static native long new_COMVS_WIFIDEVICE_EAPOL_PARAMS();

	public final static native void delete_COMVS_WIFIDEVICE_EAPOL_PARAMS(
			long jarg1);

	public final static native void COMVS_WIFIDEVICE_WEP_CONFIGURATION_ulWEP_key_index_set(
			long jarg1, COMVS_WIFIDEVICE_WEP_CONFIGURATION jarg1_, long jarg2);

	public final static native long COMVS_WIFIDEVICE_WEP_CONFIGURATION_ulWEP_key_index_get(
			long jarg1, COMVS_WIFIDEVICE_WEP_CONFIGURATION jarg1_);

	public final static native void COMVS_WIFIDEVICE_WEP_CONFIGURATION_ulWEP_key_size_set(
			long jarg1, COMVS_WIFIDEVICE_WEP_CONFIGURATION jarg1_, long jarg2);

	public final static native long COMVS_WIFIDEVICE_WEP_CONFIGURATION_ulWEP_key_size_get(
			long jarg1, COMVS_WIFIDEVICE_WEP_CONFIGURATION jarg1_);

	public final static native void COMVS_WIFIDEVICE_WEP_CONFIGURATION_ucWEP_key_set(
			long jarg1, COMVS_WIFIDEVICE_WEP_CONFIGURATION jarg1_, String jarg2);

	public final static native String COMVS_WIFIDEVICE_WEP_CONFIGURATION_ucWEP_key_get(
			long jarg1, COMVS_WIFIDEVICE_WEP_CONFIGURATION jarg1_);

	public final static native void COMVS_WIFIDEVICE_WEP_CONFIGURATION_reserved_set(
			long jarg1, COMVS_WIFIDEVICE_WEP_CONFIGURATION jarg1_, long jarg2);

	public final static native long COMVS_WIFIDEVICE_WEP_CONFIGURATION_reserved_get(
			long jarg1, COMVS_WIFIDEVICE_WEP_CONFIGURATION jarg1_);

	public final static native long new_COMVS_WIFIDEVICE_WEP_CONFIGURATION();

	public final static native void delete_COMVS_WIFIDEVICE_WEP_CONFIGURATION(
			long jarg1);

	public final static native void COMVS_WIFIDEVICE_CONFIGURATION_ucSSID_set(
			long jarg1, COMVS_WIFIDEVICE_CONFIGURATION jarg1_, String jarg2);

	public final static native String COMVS_WIFIDEVICE_CONFIGURATION_ucSSID_get(
			long jarg1, COMVS_WIFIDEVICE_CONFIGURATION jarg1_);

	public final static native void COMVS_WIFIDEVICE_CONFIGURATION_iWifi_mode_authentication_set(
			long jarg1, COMVS_WIFIDEVICE_CONFIGURATION jarg1_, int jarg2);

	public final static native int COMVS_WIFIDEVICE_CONFIGURATION_iWifi_mode_authentication_get(
			long jarg1, COMVS_WIFIDEVICE_CONFIGURATION jarg1_);

	public final static native void COMVS_WIFIDEVICE_CONFIGURATION_iMode_infrastructure_set(
			long jarg1, COMVS_WIFIDEVICE_CONFIGURATION jarg1_, int jarg2);

	public final static native int COMVS_WIFIDEVICE_CONFIGURATION_iMode_infrastructure_get(
			long jarg1, COMVS_WIFIDEVICE_CONFIGURATION jarg1_);

	public final static native void COMVS_WIFIDEVICE_CONFIGURATION_ulMode_cipher_set(
			long jarg1, COMVS_WIFIDEVICE_CONFIGURATION jarg1_, long jarg2);

	public final static native long COMVS_WIFIDEVICE_CONFIGURATION_ulMode_cipher_get(
			long jarg1, COMVS_WIFIDEVICE_CONFIGURATION jarg1_);

	public final static native void COMVS_WIFIDEVICE_CONFIGURATION_stWEP_config_set(
			long jarg1, COMVS_WIFIDEVICE_CONFIGURATION jarg1_, long jarg2,
			COMVS_WIFIDEVICE_WEP_CONFIGURATION jarg2_);

	public final static native long COMVS_WIFIDEVICE_CONFIGURATION_stWEP_config_get(
			long jarg1, COMVS_WIFIDEVICE_CONFIGURATION jarg1_);

	public final static native void COMVS_WIFIDEVICE_CONFIGURATION_st802_1x_mode_authentication_set(
			long jarg1, COMVS_WIFIDEVICE_CONFIGURATION jarg1_, long jarg2,
			COMVS_WIFIDEVICE_EAPOL_PARAMS jarg2_);

	public final static native long COMVS_WIFIDEVICE_CONFIGURATION_st802_1x_mode_authentication_get(
			long jarg1, COMVS_WIFIDEVICE_CONFIGURATION jarg1_);

	public final static native void COMVS_WIFIDEVICE_CONFIGURATION_nbOfConfig_set(
			long jarg1, COMVS_WIFIDEVICE_CONFIGURATION jarg1_, long jarg2);

	public final static native long COMVS_WIFIDEVICE_CONFIGURATION_nbOfConfig_get(
			long jarg1, COMVS_WIFIDEVICE_CONFIGURATION jarg1_);

	public final static native void COMVS_WIFIDEVICE_CONFIGURATION_reserved_set(
			long jarg1, COMVS_WIFIDEVICE_CONFIGURATION jarg1_, long jarg2);

	public final static native long COMVS_WIFIDEVICE_CONFIGURATION_reserved_get(
			long jarg1, COMVS_WIFIDEVICE_CONFIGURATION jarg1_);

	public final static native long new_COMVS_WIFIDEVICE_CONFIGURATION();

	public final static native void delete_COMVS_WIFIDEVICE_CONFIGURATION(
			long jarg1);

	public final static native short Comvs_IsWifiCard();

	public final static native short Comvs_IsConnectedToNetwork();

	public final static native int Comvs_SetWifiPreferedNetwork(long jarg1,
			COMVS_WIFIDEVICE_CONFIGURATION jarg1_);

	public final static native int Comvs_DeleteWifiPreferedNetwork(String jarg1);

	public final static native int Comvs_DeleteWifiPreferedNetworks();

	public final static native int Comvs_GetSignalStrength(long jarg1);
}
