/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.fm6000.wifi.jni;

public class COMVS_WIFIDEVICE_CONFIGURATION {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected COMVS_WIFIDEVICE_CONFIGURATION(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(COMVS_WIFIDEVICE_CONFIGURATION obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			COMVS_WIFIJNI.delete_COMVS_WIFIDEVICE_CONFIGURATION(swigCPtr);
		}
		swigCPtr = 0;
	}

	public void setUcSSID(String value) {
		COMVS_WIFIJNI.COMVS_WIFIDEVICE_CONFIGURATION_ucSSID_set(swigCPtr, this,
				value);
	}

	public String getUcSSID() {
		return COMVS_WIFIJNI.COMVS_WIFIDEVICE_CONFIGURATION_ucSSID_get(
				swigCPtr, this);
	}

	public void setIWifi_mode_authentication(int value) {
		COMVS_WIFIJNI
				.COMVS_WIFIDEVICE_CONFIGURATION_iWifi_mode_authentication_set(
						swigCPtr, this, value);
	}

	public int getIWifi_mode_authentication() {
		return COMVS_WIFIJNI
				.COMVS_WIFIDEVICE_CONFIGURATION_iWifi_mode_authentication_get(
						swigCPtr, this);
	}

	public void setIMode_infrastructure(int value) {
		COMVS_WIFIJNI.COMVS_WIFIDEVICE_CONFIGURATION_iMode_infrastructure_set(
				swigCPtr, this, value);
	}

	public int getIMode_infrastructure() {
		return COMVS_WIFIJNI
				.COMVS_WIFIDEVICE_CONFIGURATION_iMode_infrastructure_get(
						swigCPtr, this);
	}

	public void setUlMode_cipher(long value) {
		COMVS_WIFIJNI.COMVS_WIFIDEVICE_CONFIGURATION_ulMode_cipher_set(
				swigCPtr, this, value);
	}

	public long getUlMode_cipher() {
		return COMVS_WIFIJNI.COMVS_WIFIDEVICE_CONFIGURATION_ulMode_cipher_get(
				swigCPtr, this);
	}

	public void setStWEP_config(COMVS_WIFIDEVICE_WEP_CONFIGURATION value) {
		COMVS_WIFIJNI.COMVS_WIFIDEVICE_CONFIGURATION_stWEP_config_set(swigCPtr,
				this, COMVS_WIFIDEVICE_WEP_CONFIGURATION.getCPtr(value), value);
	}

	public COMVS_WIFIDEVICE_WEP_CONFIGURATION getStWEP_config() {
		long cPtr = COMVS_WIFIJNI
				.COMVS_WIFIDEVICE_CONFIGURATION_stWEP_config_get(swigCPtr, this);
		return (cPtr == 0) ? null : new COMVS_WIFIDEVICE_WEP_CONFIGURATION(
				cPtr, false);
	}

	public void setSt802_1x_mode_authentication(
			COMVS_WIFIDEVICE_EAPOL_PARAMS value) {
		COMVS_WIFIJNI
				.COMVS_WIFIDEVICE_CONFIGURATION_st802_1x_mode_authentication_set(
						swigCPtr, this, COMVS_WIFIDEVICE_EAPOL_PARAMS
								.getCPtr(value), value);
	}

	public COMVS_WIFIDEVICE_EAPOL_PARAMS getSt802_1x_mode_authentication() {
		long cPtr = COMVS_WIFIJNI
				.COMVS_WIFIDEVICE_CONFIGURATION_st802_1x_mode_authentication_get(
						swigCPtr, this);
		return (cPtr == 0) ? null : new COMVS_WIFIDEVICE_EAPOL_PARAMS(cPtr,
				false);
	}

	public void setNbOfConfig(long value) {
		COMVS_WIFIJNI.COMVS_WIFIDEVICE_CONFIGURATION_nbOfConfig_set(swigCPtr,
				this, value);
	}

	public long getNbOfConfig() {
		return COMVS_WIFIJNI.COMVS_WIFIDEVICE_CONFIGURATION_nbOfConfig_get(
				swigCPtr, this);
	}

	public void setReserved(SWIGTYPE_p_void value) {
		COMVS_WIFIJNI.COMVS_WIFIDEVICE_CONFIGURATION_reserved_set(swigCPtr,
				this, SWIGTYPE_p_void.getCPtr(value));
	}

	public SWIGTYPE_p_void getReserved() {
		long cPtr = COMVS_WIFIJNI.COMVS_WIFIDEVICE_CONFIGURATION_reserved_get(
				swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
	}

	public COMVS_WIFIDEVICE_CONFIGURATION() {
		this(COMVS_WIFIJNI.new_COMVS_WIFIDEVICE_CONFIGURATION(), true);
	}

}
