/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_avm_device_connection_mux_Connection */

#ifndef _Included_org_avm_device_connection_mux_Connection
#define _Included_org_avm_device_connection_mux_Connection
#ifdef __cplusplus
extern "C" {
#endif
#undef org_avm_device_connection_mux_Connection_DEFAULT_TIMEOUT
#define org_avm_device_connection_mux_Connection_DEFAULT_TIMEOUT 3000L
#undef org_avm_device_connection_mux_Connection_PARITY_NONE
#define org_avm_device_connection_mux_Connection_PARITY_NONE 0L
#undef org_avm_device_connection_mux_Connection_PARITY_ODD
#define org_avm_device_connection_mux_Connection_PARITY_ODD 1L
#undef org_avm_device_connection_mux_Connection_PARITY_EVEN
#define org_avm_device_connection_mux_Connection_PARITY_EVEN 2L
#undef org_avm_device_connection_mux_Connection_UNOPENED
#define org_avm_device_connection_mux_Connection_UNOPENED 0L
#undef org_avm_device_connection_mux_Connection_OPEN
#define org_avm_device_connection_mux_Connection_OPEN 1L
#undef org_avm_device_connection_mux_Connection_CLOSED
#define org_avm_device_connection_mux_Connection_CLOSED 2L
/*
 * Class:     org_avm_device_connection_mux_Connection
 * Method:    openImpl
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_connection_mux_Connection_openImpl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_avm_device_connection_mux_Connection
 * Method:    configureImpl
 * Signature: (IIIIIZZI)V
 */
JNIEXPORT void JNICALL Java_org_avm_device_connection_mux_Connection_configureImpl
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jboolean, jboolean, jint);

/*
 * Class:     org_avm_device_connection_mux_Connection
 * Method:    closeImpl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_avm_device_connection_mux_Connection_closeImpl
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_avm_device_connection_mux_Connection
 * Method:    readImpl
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_connection_mux_Connection_readImpl
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     org_avm_device_connection_mux_Connection
 * Method:    writeImpl
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_connection_mux_Connection_writeImpl
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     org_avm_device_connection_mux_Connection
 * Method:    availableImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_connection_mux_Connection_availableImpl
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
