/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_avm_device_protocol_comm_CommConnection */

#ifndef _Included_org_avm_device_protocol_comm_CommConnection
#define _Included_org_avm_device_protocol_comm_CommConnection
#ifdef __cplusplus
extern "C" {
#endif
#undef org_avm_device_protocol_comm_CommConnection_B300
#define org_avm_device_protocol_comm_CommConnection_B300 300L
#undef org_avm_device_protocol_comm_CommConnection_B600
#define org_avm_device_protocol_comm_CommConnection_B600 600L
#undef org_avm_device_protocol_comm_CommConnection_B1200
#define org_avm_device_protocol_comm_CommConnection_B1200 1200L
#undef org_avm_device_protocol_comm_CommConnection_B2400
#define org_avm_device_protocol_comm_CommConnection_B2400 2400L
#undef org_avm_device_protocol_comm_CommConnection_B4800
#define org_avm_device_protocol_comm_CommConnection_B4800 4800L
#undef org_avm_device_protocol_comm_CommConnection_B9600
#define org_avm_device_protocol_comm_CommConnection_B9600 9600L
#undef org_avm_device_protocol_comm_CommConnection_B19200
#define org_avm_device_protocol_comm_CommConnection_B19200 19200L
#undef org_avm_device_protocol_comm_CommConnection_B38400
#define org_avm_device_protocol_comm_CommConnection_B38400 38400L
#undef org_avm_device_protocol_comm_CommConnection_B57600
#define org_avm_device_protocol_comm_CommConnection_B57600 57600L
#undef org_avm_device_protocol_comm_CommConnection_B115200
#define org_avm_device_protocol_comm_CommConnection_B115200 115200L
#undef org_avm_device_protocol_comm_CommConnection_B230400
#define org_avm_device_protocol_comm_CommConnection_B230400 230400L
#undef org_avm_device_protocol_comm_CommConnection_STOPBITS1
#define org_avm_device_protocol_comm_CommConnection_STOPBITS1 0L
#undef org_avm_device_protocol_comm_CommConnection_STOPBITS2
#define org_avm_device_protocol_comm_CommConnection_STOPBITS2 1L
#undef org_avm_device_protocol_comm_CommConnection_PARITY_ODD
#define org_avm_device_protocol_comm_CommConnection_PARITY_ODD 2L
#undef org_avm_device_protocol_comm_CommConnection_PARITY_EVEN
#define org_avm_device_protocol_comm_CommConnection_PARITY_EVEN 4L
#undef org_avm_device_protocol_comm_CommConnection_AUTORTS
#define org_avm_device_protocol_comm_CommConnection_AUTORTS 16L
#undef org_avm_device_protocol_comm_CommConnection_AUTOCTS
#define org_avm_device_protocol_comm_CommConnection_AUTOCTS 32L
#undef org_avm_device_protocol_comm_CommConnection_BITSPERCHAR7
#define org_avm_device_protocol_comm_CommConnection_BITSPERCHAR7 64L
#undef org_avm_device_protocol_comm_CommConnection_BITSPERCHAR8
#define org_avm_device_protocol_comm_CommConnection_BITSPERCHAR8 128L
#undef org_avm_device_protocol_comm_CommConnection_READ
#define org_avm_device_protocol_comm_CommConnection_READ 1L
#undef org_avm_device_protocol_comm_CommConnection_WRITE
#define org_avm_device_protocol_comm_CommConnection_WRITE 2L
#undef org_avm_device_protocol_comm_CommConnection_READ_WRITE
#define org_avm_device_protocol_comm_CommConnection_READ_WRITE 3L
#undef org_avm_device_protocol_comm_CommConnection_UNOPENED
#define org_avm_device_protocol_comm_CommConnection_UNOPENED 0L
#undef org_avm_device_protocol_comm_CommConnection_OPENED
#define org_avm_device_protocol_comm_CommConnection_OPENED 1L
#undef org_avm_device_protocol_comm_CommConnection_CLOSED
#define org_avm_device_protocol_comm_CommConnection_CLOSED 2L
#undef org_avm_device_protocol_comm_CommConnection_DEFAULT_TIMEOUT
#define org_avm_device_protocol_comm_CommConnection_DEFAULT_TIMEOUT 3000L
#undef org_avm_device_protocol_comm_CommConnection_BUFFERSIZE
#define org_avm_device_protocol_comm_CommConnection_BUFFERSIZE 255L
/*
 * Class:     org_avm_device_protocol_comm_CommConnection
 * Method:    openImpl
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_protocol_comm_CommConnection_openImpl
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_avm_device_protocol_comm_CommConnection
 * Method:    closeImpl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_avm_device_protocol_comm_CommConnection_closeImpl
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_avm_device_protocol_comm_CommConnection
 * Method:    readImpl
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_protocol_comm_CommConnection_readImpl
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     org_avm_device_protocol_comm_CommConnection
 * Method:    writeImpl
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_org_avm_device_protocol_comm_CommConnection_writeImpl
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     org_avm_device_protocol_comm_CommConnection
 * Method:    availableImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_protocol_comm_CommConnection_availableImpl
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
