/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.nomad.io.jni;

public class NOMAD_IO {
  public static int dio_open(String name) {
    return NOMAD_IOJNI.dio_open(name);
  }

  public static void dio_close(int handle) {
    NOMAD_IOJNI.dio_close(handle);
  }

  public static int dio_read_input(int handle) {
    return NOMAD_IOJNI.dio_read_input(handle);
  }

  public static int dio_write_ouput(int handle, int value, int mask) {
    return NOMAD_IOJNI.dio_write_ouput(handle, value, mask);
  }

  public static int dio_read_counter(int handle, int id) {
    return NOMAD_IOJNI.dio_read_counter(handle, id);
  }

  public static int adc_open(String name) {
    return NOMAD_IOJNI.adc_open(name);
  }

  public static void adc_close(int handle) {
    NOMAD_IOJNI.adc_close(handle);
  }

  public static int adc_read_input(int handle, int id) {
    return NOMAD_IOJNI.adc_read_input(handle, id);
  }

}
