/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.fm6000.screen.jni;

public interface COMVS_NIGHTMODEConstants {
	public final static int COMVS_TRUE = COMVS_NIGHTMODEJNI.COMVS_TRUE_get();
	public final static int COMVS_FALSE = COMVS_NIGHTMODEJNI.COMVS_FALSE_get();
}
