/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.fm6000.screen.jni;

public class COMVS_NIGHTMODE implements COMVS_NIGHTMODEConstants {
	public static short Comvs_SetScreenMode(short invert, int percent) {
		return COMVS_NIGHTMODEJNI.Comvs_SetScreenMode(invert, percent);
	}

}
