/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_avm_device_protocol_rs485_Rs485Connection */

#ifndef _Included_org_avm_device_protocol_rs485_Rs485Connection
#define _Included_org_avm_device_protocol_rs485_Rs485Connection
#ifdef __cplusplus
extern "C" {
#endif
#undef org_avm_device_protocol_rs485_Rs485Connection_B300
#define org_avm_device_protocol_rs485_Rs485Connection_B300 300L
#undef org_avm_device_protocol_rs485_Rs485Connection_B600
#define org_avm_device_protocol_rs485_Rs485Connection_B600 600L
#undef org_avm_device_protocol_rs485_Rs485Connection_B1200
#define org_avm_device_protocol_rs485_Rs485Connection_B1200 1200L
#undef org_avm_device_protocol_rs485_Rs485Connection_B2400
#define org_avm_device_protocol_rs485_Rs485Connection_B2400 2400L
#undef org_avm_device_protocol_rs485_Rs485Connection_B4800
#define org_avm_device_protocol_rs485_Rs485Connection_B4800 4800L
#undef org_avm_device_protocol_rs485_Rs485Connection_B9600
#define org_avm_device_protocol_rs485_Rs485Connection_B9600 9600L
#undef org_avm_device_protocol_rs485_Rs485Connection_B19200
#define org_avm_device_protocol_rs485_Rs485Connection_B19200 19200L
#undef org_avm_device_protocol_rs485_Rs485Connection_B38400
#define org_avm_device_protocol_rs485_Rs485Connection_B38400 38400L
#undef org_avm_device_protocol_rs485_Rs485Connection_B57600
#define org_avm_device_protocol_rs485_Rs485Connection_B57600 57600L
#undef org_avm_device_protocol_rs485_Rs485Connection_B115200
#define org_avm_device_protocol_rs485_Rs485Connection_B115200 115200L
#undef org_avm_device_protocol_rs485_Rs485Connection_B230400
#define org_avm_device_protocol_rs485_Rs485Connection_B230400 230400L
#undef org_avm_device_protocol_rs485_Rs485Connection_STOPBITS1
#define org_avm_device_protocol_rs485_Rs485Connection_STOPBITS1 0L
#undef org_avm_device_protocol_rs485_Rs485Connection_STOPBITS2
#define org_avm_device_protocol_rs485_Rs485Connection_STOPBITS2 1L
#undef org_avm_device_protocol_rs485_Rs485Connection_PARITY_ODD
#define org_avm_device_protocol_rs485_Rs485Connection_PARITY_ODD 2L
#undef org_avm_device_protocol_rs485_Rs485Connection_PARITY_EVEN
#define org_avm_device_protocol_rs485_Rs485Connection_PARITY_EVEN 4L
#undef org_avm_device_protocol_rs485_Rs485Connection_AUTORTS
#define org_avm_device_protocol_rs485_Rs485Connection_AUTORTS 16L
#undef org_avm_device_protocol_rs485_Rs485Connection_AUTOCTS
#define org_avm_device_protocol_rs485_Rs485Connection_AUTOCTS 32L
#undef org_avm_device_protocol_rs485_Rs485Connection_BITSPERCHAR7
#define org_avm_device_protocol_rs485_Rs485Connection_BITSPERCHAR7 64L
#undef org_avm_device_protocol_rs485_Rs485Connection_BITSPERCHAR8
#define org_avm_device_protocol_rs485_Rs485Connection_BITSPERCHAR8 128L
#undef org_avm_device_protocol_rs485_Rs485Connection_READ
#define org_avm_device_protocol_rs485_Rs485Connection_READ 1L
#undef org_avm_device_protocol_rs485_Rs485Connection_WRITE
#define org_avm_device_protocol_rs485_Rs485Connection_WRITE 2L
#undef org_avm_device_protocol_rs485_Rs485Connection_READ_WRITE
#define org_avm_device_protocol_rs485_Rs485Connection_READ_WRITE 3L
#undef org_avm_device_protocol_rs485_Rs485Connection_UNOPENED
#define org_avm_device_protocol_rs485_Rs485Connection_UNOPENED 0L
#undef org_avm_device_protocol_rs485_Rs485Connection_OPENED
#define org_avm_device_protocol_rs485_Rs485Connection_OPENED 1L
#undef org_avm_device_protocol_rs485_Rs485Connection_CLOSED
#define org_avm_device_protocol_rs485_Rs485Connection_CLOSED 2L
#undef org_avm_device_protocol_rs485_Rs485Connection_DEFAULT_TIMEOUT
#define org_avm_device_protocol_rs485_Rs485Connection_DEFAULT_TIMEOUT 3000L
#undef org_avm_device_protocol_rs485_Rs485Connection_BUFFERSIZE
#define org_avm_device_protocol_rs485_Rs485Connection_BUFFERSIZE 255L
/*
 * Class:     org_avm_device_protocol_rs485_Rs485Connection
 * Method:    openImpl
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_protocol_rs485_Rs485Connection_openImpl
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_avm_device_protocol_rs485_Rs485Connection
 * Method:    closeImpl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_avm_device_protocol_rs485_Rs485Connection_closeImpl
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_avm_device_protocol_rs485_Rs485Connection
 * Method:    readImpl
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_protocol_rs485_Rs485Connection_readImpl
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     org_avm_device_protocol_rs485_Rs485Connection
 * Method:    writeImpl
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_org_avm_device_protocol_rs485_Rs485Connection_writeImpl
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     org_avm_device_protocol_rs485_Rs485Connection
 * Method:    availableImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_avm_device_protocol_rs485_Rs485Connection_availableImpl
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
