/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.road.klkpic.jni;

public class KLK_PIC {
  public static int klkpic_open(String name) {
    return KLK_PICJNI.klkpic_open(name);
  }

  public static void klkpic_close(int handle) {
    KLK_PICJNI.klkpic_close(handle);
  }

  public static int klkpic_read_apc(int handle) {
    return KLK_PICJNI.klkpic_read_apc(handle);
  }

  public static int klkpic_read_wakeup(int handle) {
    return KLK_PICJNI.klkpic_read_wakeup(handle);
  }

  public static void klkpic_keep_alive() {
    KLK_PICJNI.klkpic_keep_alive();
  }

}
