/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.avm.device.road.klkpic.jni;

class KLK_PICJNI {

  static {
    try {
        System.loadLibrary("klk_pic");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
    }
  }

  public final static native int klkpic_open(String jarg1);
  public final static native void klkpic_close(int jarg1);
  public final static native int klkpic_read_apc(int jarg1);
  public final static native int klkpic_read_wakeup(int jarg1);
  public final static native void klkpic_keep_alive();
}
