/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package org.avm.device.fm6000.mp3.jni;

public class COMVS_MP3 {

	public static void initialize() {
		COMVS_MP3JNI.initialize();
	}

	public static void dispose() {
		COMVS_MP3JNI.dispose();
	}

	public static long open(String name) {
		return COMVS_MP3JNI.open(name);
	}

	public static void play(long handle) {
		COMVS_MP3JNI.play(handle);
	}

	public static void pause(long handle) {
		COMVS_MP3JNI.pause(handle);
	}

	public static void resume(long handle) {
		COMVS_MP3JNI.resume(handle);
	}

	public static void stop(long handle) {
		COMVS_MP3JNI.stop(handle);
	}

	public static void close(long handle) {
		COMVS_MP3JNI.close(handle);
	}
}
